Repository ChainSafe/ui-monorepo, pull requests merged in 2021-07, with the labels that each got.

#1048 Sharing file browser
  packages/files-ui/src/Components/FilesRoutes.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFolderRowWrapper.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/Sharing/ShareFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/SharesList.tsx
  packages/files-ui/src/Components/Pages/ShareFilesPage.tsx
  packages/files-ui/src/Contexts/FileBrowserContext.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1217 Refactor File info modal
  packages/files-ui/src/Components/Modules/FileBrowsers/FileInfoModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/SharesList.tsx
Labels: Status: Review Needed 👀, Type: Maintenance

#1201 Create shared folder modal
  packages/common-components/src/SelectInput/SelectInput.tsx
  packages/common-components/src/TagsInput/TagsInput.tsx
  packages/common-components/src/TagsInput/index.ts
  packages/common-components/src/TextInput/TextInput.tsx
  packages/common-components/src/index.ts
  packages/common-components/src/stories/TagsInput.stories.tsx
  packages/common-theme/src/Overrides/TagsInput.ts
  packages/common-theme/src/Overrides/index.ts
  packages/files-ui/package.json
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/Settings/Profile.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/Contexts/UserContext.tsx
  packages/files-ui/src/Themes/Constants.ts
  packages/files-ui/src/Themes/DarkTheme.ts
  packages/files-ui/src/Themes/LightTheme.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/storage-ui/package.json
  yarn.lock
Labels: Status: Review Needed 👀, Type: Feature

#1202 Support file and folder deletion
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/Utils/pathUtils.ts
Labels: Status: Review Needed 👀, Type: Feature

#1221 Use BucketKeyPermission instead of missleading Bucket
  packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFolderRowWrapper.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/Contexts/FileBrowserContext.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
Labels: Status: Review Needed 👀, Type: Maintenance

#1197 Rename shared folder
  packages/common-components/src/SelectInput/SelectInput.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFolderRowWrapper.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/Contexts/FileBrowserContext.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/locales/de/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1220 Bump cypress to v1.7
  packages/files-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: Status: Review Needed 👀, Type: Maintenance

#1219 Unify FilesList and SharesList
  packages/files-ui/src/Components/Modules/FileBrowsers/Sharing/ShareFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/SharesList.tsx
  packages/files-ui/src/Contexts/FileBrowserContext.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Maintenance

#1223 Fix bucket filtering in Share browser
  packages/files-ui/src/Components/Modules/FileBrowsers/Sharing/ShareFileBrowser.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1228 Resolve preview error
  packages/files-ui/src/Components/Modules/FilePreviewModal.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1229 Move files tree in shared folder
  packages/files-ui/src/Components/Modules/FileBrowsers/MoveFileModal.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Bug Fix

#1231 Fix bulk operations for csf buckets
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1232 Fix shared folder creation path
  packages/files-ui/src/Components/FilesRoutes.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/MoveFileModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/Sharing/ShareFileBrowser.tsx
  packages/files-ui/src/Utils/pathUtils.ts
Labels: Status: Review Needed 👀, Type: Bug Fix

#1235 Fix refresh token flow
  packages/files-ui/src/Contexts/FilesApiContext.tsx
Labels: Release: Patch, Status: Review Needed 👀, Type: Bug Fix

#1240 Automate extract for storage
  .github/workflows/lingui-extract-files.yml
  .github/workflows/lingui-extract-storage.yml
  packages/storage-ui/src/locales/en/messages.po
Labels: Status: Review Needed 👀, Type: Bug Fix

#1225 Owner column in shared folder overview
  packages/files-ui/src/Components/Elements/SharedUser.tsx
  packages/files-ui/src/Components/Elements/UserBubble.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1239 Use npm regisry
  .env.example
  .github/workflows/lingui-extract-files.yml
  .github/workflows/lint.yml
  .github/workflows/test-files.yml
  .github/workflows/test-storage.yml
  .npmrc
  README.md
  packages/files-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: Status: Review Needed 👀, Type: Maintenance

#1233 fix recover files from trash folder tree
  packages/files-ui/src/Components/Modules/FileBrowsers/MoveFileModal.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1168 ES Locale
  packages/files-ui/.linguirc
  packages/files-ui/src/App.tsx
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
Labels: Type: Feature

#1242 Fix web3 login flow for storage
  packages/files-ui/package.json
  packages/storage-ui/package.json
  packages/storage-ui/src/Components/Modules/LoginModule.tsx
  packages/storage-ui/src/Components/Pages/OAuthCallback.tsx
  packages/storage-ui/src/Contexts/StorageApiContext.tsx
  yarn.lock
Labels: Status: Review Needed 👀, Type: Maintenance

#1241 Delete files & folders from shared folders directly.
  packages/files-ui/src/Components/Modules/FileBrowsers/Sharing/ShareFileBrowser.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1254 Remove hotjar
  packages/files-ui/package.json
  packages/files-ui/src/App.tsx
Labels: Status: Review Needed 👀, Type: Maintenance

#1245 Clean locally stored cache files before running tests
  package.json
  packages/files-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: Status: Review Needed 👀, Type: Maintenance

#1227 Reporting Illegal content
  packages/files-ui/src/Components/FilesRoutes.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/FileInfoModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ReportFileModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/Sharing/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/types.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Pages/ShareFilesPage.tsx
  packages/files-ui/src/Components/Pages/SharedFilesPage.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1248 DirectAuth updates for Storage
  packages/files-ui/.env.example
  packages/files-ui/src/Contexts/ThresholdKeyContext.tsx
  packages/storage-ui/src/Components/Modules/LoginModule.tsx
  packages/storage-ui/src/Components/Modules/LoginModule/PasswordlessEmail.tsx
  packages/storage-ui/src/Contexts/StorageApiContext.tsx
  packages/storage-ui/src/locales/en/messages.po
Labels: Epic: Storage v0, Status: Review Needed 👀, Type: Feature

#1260 settings layout for storage
  packages/storage-ui/src/Components/Modules/ApiKeys.tsx
  packages/storage-ui/src/Components/Pages/SettingsPage.tsx
  packages/storage-ui/src/Components/StorageRoutes.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1259 delete bulk operation
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1257 Sorted by dates by default
  packages/storage-ui/src/Components/Pages/CidsPage.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1258 Create bucket modal changes
  packages/storage-ui/src/Components/Pages/BucketsPage.tsx
  packages/storage-ui/src/Contexts/StorageContext.tsx
  packages/storage-ui/src/locales/en/messages.po
Labels: Status: Review Needed 👀, Type: Bug Fix

#1263 Update to the new repo url
  README.md
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/ReportFileModal.tsx
  packages/gaming-ui/cypress/support/page-objects/homePage.ts
  packages/storage-ui/cypress/support/page-objects/homePage.ts
Labels: Status: Review Needed 👀, Type: Maintenance

#1262 Add survey to Storage
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Modules/SurveyBanner.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/Components/StorageRoutes.tsx
  packages/storage-ui/src/locales/en/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1268 Don't show the pinning bucket in the bucket list
  packages/storage-ui/src/Contexts/StorageContext.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1255 Copy file to shared folder
  packages/common-components/src/TagsInput/TagsInput.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CopyToSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useCreateSharedFolder.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useGetFile.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useLookupUser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/types.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Modules/FilePreviewModal.tsx
  packages/files-ui/src/Components/Pages/SharedFilesPage.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1278 Fix bulk action
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1236 Storage-ui: Add identifiers for page objects and basic bucket test
  packages/files-ui/cypress/support/page-objects/basePage.ts
  packages/files-ui/cypress/support/page-objects/navigationMenu.ts
  packages/files-ui/src/Components/Layouts/AppHeader.tsx
  packages/files-ui/src/Components/Layouts/AppNav.tsx
  packages/gaming-ui/src/Components/Layouts/AppNav.tsx
  packages/storage-ui/cypress/fixtures/storageTestData.ts
  packages/storage-ui/cypress/support/commands.ts
  packages/storage-ui/cypress/support/page-objects/basePage.ts
  packages/storage-ui/cypress/support/page-objects/bucketsPage.ts
  packages/storage-ui/cypress/support/page-objects/cidsPage.ts
  packages/storage-ui/cypress/support/page-objects/homePage.ts
  packages/storage-ui/cypress/support/page-objects/navigationMenu.ts
  packages/storage-ui/cypress/support/utils/apiTestHelper.ts
  packages/storage-ui/cypress/tests/bucket-management-spec.ts
  packages/storage-ui/cypress/tests/cid-management-spec.ts
  packages/storage-ui/cypress/tests/main-navigation-spec.ts
  packages/storage-ui/src/Components/Elements/BucketRow.tsx
  packages/storage-ui/src/Components/Elements/CidRow.tsx
  packages/storage-ui/src/Components/Layouts/AppHeader.tsx
  packages/storage-ui/src/Components/Layouts/AppNav.tsx
  packages/storage-ui/src/Components/Modules/AddCIDModal.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Pages/BucketsPage.tsx
  packages/storage-ui/src/Components/Pages/CidsPage.tsx
Labels: Type: Maintenance

#1277 Fix to prevent from moving folders in sub-folders
  packages/files-ui/src/Components/Modules/FileBrowsers/MoveFileModal.tsx
  packages/files-ui/src/Utils/pathUtils.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/storage-ui/src/Components/Modules/MoveFileModal/MoveFileModal.tsx
  packages/storage-ui/src/Utils/pathUtils.ts
  packages/storage-ui/src/locales/en/messages.po
Labels: Status: Review Needed 👀, Type: Bug Fix

#1287 Exporting the hash router
  package.json
  packages/common-components/package.json
  packages/common-components/src/Router/index.ts
Labels: Type: Feature

#1288 Fix rename issue
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Utils/validationSchema.ts
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemGridItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Utils/validationSchema.ts
  packages/storage-ui/src/locales/en/messages.po
Labels: Status: Review Needed 👀, Type: Bug Fix

#1292 Suggestions for shared folder permission update
  packages/files-ui/src/Components/Modules/FileBrowsers/UpdateSharedFolderModal.tsx
Labels: Status: Review Needed 👀

#1291 Text Input Icon Cursor
  packages/common-components/src/TextInput/TextInput.tsx
Labels: Status: Review Needed 👀

#1269 Edit shared folder by owner
  packages/common-components/src/Icons/icons/Update.icon.tsx
  packages/common-components/src/Icons/index.ts
  packages/common-components/src/Icons/svgs/update.svg
  packages/common-components/src/TagsInput/TagsInput.tsx
  packages/common-components/src/TagsInput/index.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/EditSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFolderRowWrapper.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1302 Ensure bucket names are unique
  packages/storage-ui/src/Components/Elements/BucketRow.tsx
  packages/storage-ui/src/Components/Pages/BucketsPage.tsx
  packages/storage-ui/src/locales/en/messages.po
Labels: Status: Review Needed 👀, Type: Bug Fix

#1290 Trim before creation and renaming file, folders and buckets
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/Utils/validationSchema.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/storage-ui/src/Components/Modules/AddCIDModal.tsx
  packages/storage-ui/src/Components/Modules/CreateFolderModal/CreateFolderModal.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemGridItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
  packages/storage-ui/src/Components/Pages/BucketsPage.tsx
  packages/storage-ui/src/Utils/validationSchema.ts
  packages/storage-ui/src/locales/en/messages.po
Labels: Status: Review Needed 👀, Type: Bug Fix

#1299 how limit of 5GB on storage
  packages/storage-ui/src/Utils/Constants.ts
Labels: Type: Bug Fix

#1300 S3 API Keys
  packages/files-ui/package.json
  packages/files-ui/src/Contexts/BillingContext.tsx
  packages/gaming-ui/package.json
  packages/storage-ui/package.json
  packages/storage-ui/src/Components/Elements/SecretField.tsx
  packages/storage-ui/src/Components/Modules/ApiKeys.tsx
  packages/storage-ui/src/locales/en/messages.po
  yarn.lock
Labels: Status: Review Needed 👀, Type: Feature

#1311 Update Navigation
  packages/storage-ui/src/Components/Layouts/AppNav.tsx
  packages/storage-ui/src/Components/StorageRoutes.tsx
  packages/storage-ui/src/locales/en/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1307 Resolve move folder glitches
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Modules/MoveFileModal/MoveFileModal.tsx
  packages/storage-ui/src/Utils/pathUtils.ts
Labels: Status: Review Needed 👀, Type: Bug Fix

#1306 Fix CID validation
  packages/storage-ui/package.json
  packages/storage-ui/src/Contexts/StorageApiContext.tsx
  packages/storage-ui/src/Utils/validationSchema.ts
  yarn.lock
Labels: Status: Review Needed 👀, Type: Bug Fix

#1310 Fixing storage empty folder select
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemGridItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Modules/MoveFileModal/MoveFileModal.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/Contexts/FileBrowserContext.tsx
Labels: Epic: Storage v0, Type: Bug Fix

#1318 upload progress not working
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/storage-ui/src/Contexts/StorageContext.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1316 Escape backslash in "white space error message" regex
  packages/files-ui/src/Utils/validationSchema.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/storage-ui/src/Components/Modules/MoveFileModal/MoveFileModal.tsx
  packages/storage-ui/src/Utils/validationSchema.ts
  packages/storage-ui/src/locales/en/messages.po
Labels: Epic: Storage v0, Type: Bug Fix

#1317 fix delete confirmation label
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/locales/en/messages.po
Labels: Type: Bug Fix

#1322 Added hidden state for deleted
  packages/storage-ui/package.json
  packages/storage-ui/src/Components/Elements/BucketRow.tsx
  yarn.lock
Labels: Epic: Storage v0, Type: Feature

#1313 Update test suite checks to match latest navigation
  packages/storage-ui/cypress/support/commands.ts
  packages/storage-ui/cypress/support/page-objects/bucketsPage.ts
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Pages/BucketsPage.tsx
  packages/storage-ui/src/Components/Pages/CidsPage.tsx
Labels: Type: Maintenance

#1328 Storage: Show profile title
  packages/storage-ui/src/App.tsx
  packages/storage-ui/src/Components/Layouts/AppHeader.tsx
  packages/storage-ui/src/Contexts/UserContext.tsx
Labels: Type: Feature

#1326 Add limit 50 to lists CID call
  packages/storage-ui/src/Contexts/StorageContext.tsx
Labels: Type: Feature

#1323 Dynamic limits added
  packages/files-ui/cypress/tests/main-navigation-spec.ts
  packages/files-ui/package.json
  packages/files-ui/src/Components/Layouts/AppNav.tsx
  packages/files-ui/src/Components/Modules/Settings/Plan.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/Utils/Constants.ts
  packages/storage-ui/src/Components/Layouts/AppNav.tsx
  packages/storage-ui/src/Contexts/StorageContext.tsx
  packages/storage-ui/src/Utils/Constants.ts
Labels: Status: Review Needed 👀, Type: Feature

#1335 Storage: Update privacy and ToS links
  packages/storage-ui/src/Components/StorageRoutes.tsx
Labels: Status: Review Needed 👀

#1337 Fix Files dev
  packages/files-ui/src/Components/Modules/Settings/Plan.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1338 Storage: Unencrypted notification
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/locales/en/messages.po
Labels: Type: Feature

#1339 Edit encryption notification copy
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/locales/en/messages.po
Labels: Type: Bug Fix

#1341 storage: Resolve DnD wrong path
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemItem.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1340 Prevent creating keys on typing enter.
  packages/storage-ui/src/Components/Modules/ApiKeys.tsx
  packages/storage-ui/src/locales/en/messages.po
Labels: Status: Review Needed 👀, Type: Bug Fix

#1350 Files: Fixed reader permission
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
Labels: Product: Files, Status: Review Needed 👀, Type: Bug Fix

#1342 Make sure to always use helpers with paths
  packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/Utils/pathUtils.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/storage-ui/src/Components/Modules/CreateFolderModal/CreateFolderModal.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemItem.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/Utils/pathUtils.ts
Labels: Status: Review Needed 👀, Type: Maintenance

#1329 [FILES] Allow user to delete or remove themselves from a shared folder
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFolderRowWrapper.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Product: Files, Type: Feature

#1352 Enhance login screen with quicker email
  packages/common-components/src/Icons/icons/EthereumLogo.icon.tsx
  packages/common-components/src/Icons/index.ts
  packages/common-components/src/Icons/svgs/ethereum-logo.svg
  packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
  packages/files-ui/src/Components/Modules/LoginModule/PasswordlessEmail.tsx
  packages/files-ui/src/Utils/validationSchema.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1351 Remove submit button for renaming and useFormik everywhere
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemGridItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1367 [FILES] Improve `Manage Bucket` label and icon
  packages/common-components/src/Icons/icons/UserGroup.icon.tsx
  packages/common-components/src/Icons/index.ts
  packages/common-components/src/Icons/svgs/user-group.svg
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Bug Fix

#1365 [Files] Always allow recovery from the bin
  packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/MoveFileModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Bug Fix

#1366 [FILES] Bad request with no path when calling drive without slash
  packages/files-ui/src/Utils/pathUtils.ts
Labels: Status: Review Needed 👀, Type: Bug Fix

#1360 [STORAGE] Added filtering for filesystem type
  packages/storage-ui/package.json
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/Contexts/FileBrowserContext.tsx
  yarn.lock
Labels: Product: Storage, Status: Changes Requested ❌, Type: Bug Fix

#1364 [Files] - Don't show any success message when there's an error
  packages/files-ui/src/Components/Modules/FileBrowsers/CopyToSharedFolderModal.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
Labels: Type: Bug Fix

#1376 Clarify the license for the ui monorepo
  README.md
Labels: Status: Review Needed 👀, Type: Bug Fix

#1356 [FILES] Fixed dark mode components
  packages/common-components/src/SelectInput/SelectInput.tsx
  packages/common-components/src/TagsInput/TagsInput.tsx
  packages/common-theme/src/Overrides/SelectInput.ts
  packages/common-theme/src/Overrides/TagsInput.ts
  packages/files-ui/src/Themes/DarkTheme.ts
  packages/files-ui/src/Themes/LightTheme.ts
Labels: Product: Files, Status: Review Needed 👀, Type: Bug Fix

#1379 Fix dropdown icon color in dark mode
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
Labels: Type: Bug Fix

#1378 Remove duplicated shared icon
  packages/common-components/src/Icons/icons/UserGroup.icon.tsx
  packages/common-components/src/Icons/index.ts
  packages/common-components/src/Icons/svgs/user-group.svg
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
Labels: Type: Bug Fix

#1358 Fixed Storage summary updating
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/Contexts/StorageContext.tsx
Labels: Product: Storage, Status: Review Needed 👀, Type: Bug Fix

#1375 Make sure Lint runs after lingui commits
  .github/workflows/lingui-extract-files.yml
  .github/workflows/lingui-extract-gaming.yml
  .github/workflows/lingui-extract-storage.yml
Labels: Status: Review Needed 👀, Type: Bug Fix
