Repository ChainSafe/ui-monorepo, pull requests merged in 2021-12, with the labels that each got.

#1792 Use a new random user for every test run
  packages/files-ui/cypress/support/commands.ts
  packages/files-ui/cypress/support/page-objects/authenticationPage.ts
  packages/files-ui/cypress/support/utils/CustomBridge.ts
  packages/files-ui/cypress/tests/survey-banner-spec.ts
  packages/files-ui/src/Components/Elements/PasswordForm.tsx
  packages/files-ui/src/Components/Modules/LoginModule/ConciseExplainer.tsx
Labels: Type: Maintenance, Status: Review Needed 👀

#1789 Fix 0 randomly appearing
  packages/files-ui/src/Components/Modules/SearchModule.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1791 Fix typing issues that appeared with cypress v9.1 upgrade
  packages/files-ui/cypress/support/commands.ts
  packages/files-ui/cypress/support/page-objects/authenticationPage.ts
  packages/files-ui/cypress/support/utils/CustomBridge.ts
  packages/files-ui/cypress/support/utils/apiTestHelper.ts
  packages/files-ui/cypress/tests/survey-banner-spec.ts
  packages/files-ui/src/Components/Elements/PasswordForm.tsx
  packages/files-ui/src/Components/Modules/LoginModule/ConciseExplainer.tsx
Labels: Type: Maintenance, Status: Review Needed 👀

#1798 Edit PR template
  .github/pull_request_template.md
Labels: Type: Maintenance

#1765 Heic loader
  packages/common-components/src/Button/Button.tsx
  packages/common-components/src/Spinner/Loading.tsx
  packages/files-ui/src/Components/Elements/MnemonicForm.tsx
  packages/files-ui/src/Components/Elements/ShareTransferRequestModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/FileInfoModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/LinkList.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/SharingLink.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ReportFileModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Modules/LinkSharingModule.tsx
  packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
  packages/files-ui/src/Components/Modules/PreviewRenderers/ImagePreview.tsx
  packages/files-ui/src/Components/Modules/Settings/SavedBrowsers/index.tsx
  packages/storage-ui/src/Components/Modules/LoginModule.tsx
Labels: Type: Bug Fix

#1797 change for create
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Bug Fix, Status: Review Needed 👀

#1801 attempt fixing storybook build
  packages/common-components/package.json
Labels: Type: Maintenance, Status: Review Needed 👀

#1800 Manage default card update and delete the older one
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCardModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentCard.tsx
  packages/files-ui/src/Contexts/BillingContext.tsx
Labels: Status: Review Needed 👀

#1786 add sorting header for mobile file browser
  packages/common-components/src/Icons/icons/Sort.icon.tsx
  packages/common-components/src/Icons/index.ts
  packages/common-components/src/Icons/svgs/sort.svg
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/UI-components/Menu.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1812 Bring back signout menu on mobile
  packages/files-ui/src/Components/Layouts/AppNav.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1813 fix breaking tests
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/UI-components/Menu.tsx
  packages/files-ui/src/locales/fr/messages.po
Labels: Type: Bug Fix, Status: Review Needed 👀

#1807 Enforce props on a new line for multiline components
  .eslintrc.json
  package.json
  packages/common-components/src/Toasts/ToastContent.tsx
  packages/common-components/src/stories/Tabs.stories.tsx
  packages/common-components/src/stories/Toasts.stories.tsx
  packages/files-ui/src/Components/Elements/TeamModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/FileInfoModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/MoveFileModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SearchFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Modules/FilePreviewModal.tsx
  packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
  packages/files-ui/src/Components/Modules/Settings/Profile.tsx
  packages/files-ui/src/Components/SharingExplainerModal.tsx
  packages/files-ui/src/Contexts/PosthogContext.tsx
  packages/storage-ui/src/App.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Modules/LoginModule.tsx
  packages/storage-ui/src/Components/Modules/MoveFileModal/MoveFileModal.tsx
  packages/storage-ui/src/Components/Modules/UploadProgressModals/UploadBox.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/Components/Pages/BucketsPage.tsx
  yarn.lock
Labels: Type: Maintenance, Status: Review Needed 👀

#1816 Merge dev into epic/files-billing
  .eslintrc.json
  package.json
  packages/common-components/src/Toasts/ToastContent.tsx
  packages/common-components/src/stories/Tabs.stories.tsx
  packages/common-components/src/stories/Toasts.stories.tsx
  packages/files-ui/src/Components/Elements/NotificationsDropdown.tsx
  packages/files-ui/src/Components/Elements/TeamModal.tsx
  packages/files-ui/src/Components/Layouts/AppNav.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/FileInfoModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/LinkList.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/MoveFileModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SearchFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useSharingExplainerModalFlag.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Modules/FilePreviewModal.tsx
  packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
  packages/files-ui/src/Components/Modules/Settings/ProfileTab/index.tsx
  packages/files-ui/src/Components/SharingExplainerModal.tsx
  packages/files-ui/src/Contexts/PosthogContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/storage-ui/src/App.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Modules/LoginModule.tsx
  packages/storage-ui/src/Components/Modules/MoveFileModal/MoveFileModal.tsx
  packages/storage-ui/src/Components/Modules/UploadProgressModals/UploadBox.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/Components/Pages/BucketsPage.tsx
  yarn.lock
Labels: Type: Maintenance

#1805 Fix checkboxes in PR templage
  .github/pull_request_template.md
Labels: Type: Bug Fix, Status: Review Needed 👀

#1817 [Files] Make sure DL as zip is sequential
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/locales/fr/messages.po
Labels: Type: Bug Fix, Status: Review Needed 👀

#1826 Cleanup Norwegian translation file
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance, Status: Review Needed 👀

#1803 Add ui test coverage for link sharing
  packages/files-ui/cypress/fixtures/linkData.ts
  packages/files-ui/cypress/support/page-objects/authenticationPage.ts
  packages/files-ui/cypress/support/page-objects/fileBrowser.ts
  packages/files-ui/cypress/support/page-objects/linkSharingConfirmation.ts
  packages/files-ui/cypress/support/page-objects/modals/createSharedFolderModal.ts
  packages/files-ui/cypress/support/page-objects/modals/leaveSharedFolderModal.ts
  packages/files-ui/cypress/support/page-objects/sharedFolderContentsPage.ts
  packages/files-ui/cypress/tests/file-sharing-spec.ts
  packages/files-ui/cypress/tests/link-sharing-spec.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/LinkSharingModule.tsx
  packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
Labels: Type: Maintenance

#1804 Downgrade path
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ConfirmPlan.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/DowngradeDetails.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/PlanDetails.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/SelectPlan.tsx
  packages/files-ui/src/Components/SharingExplainerModal.tsx
  packages/files-ui/src/Contexts/BillingContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/storage-ui/src/Components/Modules/LoginModule.tsx
Labels: Status: Review Needed 👀

#1827 standardize element identifier pattern in ui tests
  packages/common-components/src/FileInput/FileInput.tsx
  packages/files-ui/cypress/support/page-objects/authenticationPage.ts
  packages/files-ui/cypress/support/page-objects/basePage.ts
  packages/files-ui/cypress/support/page-objects/fileBrowser.ts
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/cypress/support/page-objects/modals/createFolderModal.ts
  packages/files-ui/cypress/support/page-objects/modals/createSharedFolderModal.ts
  packages/files-ui/cypress/support/page-objects/modals/fileUploadModal.ts
  packages/files-ui/cypress/support/page-objects/modals/previewModal.ts
  packages/files-ui/cypress/support/page-objects/navigationMenu.ts
  packages/files-ui/cypress/support/page-objects/settingsPage.ts
  packages/files-ui/cypress/support/page-objects/sharedPage.ts
  packages/files-ui/src/Components/Layouts/AppHeader.tsx
  packages/files-ui/src/Components/Layouts/AppNav.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/UploadFileModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
  packages/files-ui/src/Components/Modules/LoginModule/MissingShares.tsx
  packages/files-ui/src/Components/Modules/LoginModule/SaveNewDevice.tsx
  packages/files-ui/src/Components/Modules/Settings/ProfileTab/index.tsx
  packages/files-ui/src/Components/Modules/Settings/SecurityTab/index.tsx
  packages/files-ui/src/Components/Modules/Settings/index.tsx
  packages/files-ui/src/UI-components/Menu.tsx
  packages/storage-ui/cypress/support/page-objects/authenticationPage.ts
  packages/storage-ui/cypress/support/page-objects/basePage.ts
  packages/storage-ui/cypress/support/page-objects/navigationMenu.ts
  packages/storage-ui/src/Components/Layouts/AppHeader.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
  packages/storage-ui/src/Components/Modules/LoginModule.tsx
  packages/storage-ui/src/Components/Modules/UploadFileModal/UploadFileModal.tsx
Labels: Type: Maintenance

#1828 Improve credit card flow
  packages/common-components/src/Modal/Modal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ConfirmPlan.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/DowngradeDetails.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/PaymentMethod.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/PlanDetails.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/SelectPlan.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Feature

#1822 Show receipts in the settings
  packages/files-ui/src/Components/Elements/InvoiceLines.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx
  packages/files-ui/src/Components/Pages/BillingHistory.tsx
  packages/files-ui/src/Contexts/BillingContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1831 Translations update from Hosted Weblate
  packages/files-ui/src/locales/fr/messages.po
Labels: Type: Maintenance
