Repository ChainSafe/ui-monorepo, pull requests merged in 2021-10, with the labels that each got.

#1604 Refresh buckets after deletion
  packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1602 Toast messages update
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Bug Fix, Status: Review Needed 👀

#1600 Translations update from Weblate
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance

#1608 Fix move single file and test
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Utils/pathUtils.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Bug Fix, Status: Review Needed 👀

#1584 Payments add card update with setup intent
  packages/files-ui/package.json
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCardModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/index.tsx
  packages/files-ui/src/Contexts/BillingContext.tsx
  packages/files-ui/src/Themes/Constants.ts
  packages/files-ui/src/Themes/DarkTheme.ts
  packages/files-ui/src/Themes/LightTheme.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  yarn.lock
Labels: Status: Review Needed 👀, Type: Feature

#1609 bump cypress to v8.5
  packages/files-ui/package.json
  packages/gaming-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: Type: Maintenance

#1591 Migrate to API local store cache
  packages/files-ui/package.json
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useSharingExplainerModalFlag.tsx
  packages/files-ui/src/Components/SharingExplainerModal.tsx
  packages/files-ui/src/Components/SurveyBanner.tsx
  packages/files-ui/src/Contexts/UserContext.tsx
  packages/files-ui/src/locales/fr/messages.po
  yarn.lock
Labels: Type: Feature

#1613 Fix `crypto` node resolve warning on common components
  packages/common-components/rollup.config.js
Labels: Type: Bug Fix

#1610 Detect and dismiss toasts in ui tests
  packages/common-components/src/Toasts/ToastContent.tsx
  packages/files-ui/cypress/support/page-objects/binPage.ts
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/cypress/support/page-objects/toasts/deleteSuccessToast.ts
  packages/files-ui/cypress/support/page-objects/toasts/moveSuccessToast.ts
  packages/files-ui/cypress/support/page-objects/toasts/uploadCompleteToast.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/src/Contexts/FilesContext.tsx
Labels: Type: Maintenance
