Repository ChainSafe/ui-monorepo, pull requests merged in 2021-06, with the labels that each got.

#1128 Import CID
  packages/files-ui/package.json
  packages/storage-ui/package.json
  packages/storage-ui/src/Components/Elements/CidRow.tsx
  packages/storage-ui/src/Components/Elements/CustomModal.tsx
  packages/storage-ui/src/Components/Elements/PinRow.tsx
  packages/storage-ui/src/Components/Layouts/AppHeader.tsx
  packages/storage-ui/src/Components/Layouts/AppNav.tsx
  packages/storage-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
  packages/storage-ui/src/Components/Modules/PinCIDModule.tsx
  packages/storage-ui/src/Components/Pages/CidsPage.tsx
  packages/storage-ui/src/Components/Pages/LoginPage.tsx
  packages/storage-ui/src/Contexts/StorageContext.tsx
  packages/storage-ui/src/Themes/Constants.ts
  packages/storage-ui/src/Themes/DarkTheme.ts
  packages/storage-ui/src/Themes/LightTheme.ts
  packages/storage-ui/src/Themes/types.ts
  yarn.lock
Labels: Type: Feature

#1142 CodeQL Security Analysis Github Action
  .github/workflows/codeql.yml
Labels: Status: Review Needed 👀, Type: Maintenance

#1144 Added web3 sign message
  packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
  packages/storage-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1133 Add username
  packages/common-components/src/TextInput/FormikTextInput.tsx
  packages/common-components/src/TextInput/TextInput.tsx
  packages/files-ui/src/Components/Modules/Settings/Profile.tsx
  packages/files-ui/src/Contexts/UserContext.tsx
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/fr/messages.po
Labels: Status: Changes Requested ❌, Type: Feature

#1139 Update readme and setup an issue template
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  README.md
  packages/files-ui/README.md
Labels: Status: Review Needed 👀, Type: Maintenance

#1143 UI Tests: bin page - delete a file
  packages/common-components/src/Button/Button.tsx
  packages/common-components/src/Dialog/Dialog.tsx
  packages/common-components/src/FileInput/FileInput.tsx
  packages/common-components/src/Modal/Modal.tsx
  packages/files-ui/cypress/support/commands.ts
  packages/files-ui/cypress/support/page-objects/binPage.ts
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/cypress/support/utils/apiTestHelper.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Modules/UploadFileModule.tsx
  packages/files-ui/src/Components/Modules/UploadProgressModals/UploadBox.tsx
Labels: Status: Review Needed 👀, Type: Maintenance

#1140 Storage buckets overview
  packages/storage-ui/src/Components/Elements/BucketRow.tsx
  packages/storage-ui/src/Components/Layouts/AppHeader.tsx
  packages/storage-ui/src/Components/Layouts/AppNav.tsx
  packages/storage-ui/src/Components/Modules/CreateFolderModal/CreateFolderModal.tsx
  packages/storage-ui/src/Components/Modules/DownloadProgressModals/DownloadBox.tsx
  packages/storage-ui/src/Components/Modules/DownloadProgressModals/index.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemGridItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
  packages/storage-ui/src/Components/Modules/FilesList/DragConstants.ts
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
  packages/storage-ui/src/Components/Modules/MoveFileModal/MoveFileModal.tsx
  packages/storage-ui/src/Components/Modules/UploadFileModal/UploadFileModal.tsx
  packages/storage-ui/src/Components/Modules/UploadProgressModals/UploadBox.tsx
  packages/storage-ui/src/Components/Modules/UploadProgressModals/index.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/Components/Pages/Buckets.tsx
  packages/storage-ui/src/Components/Pages/BucketsPage.tsx
  packages/storage-ui/src/Components/Pages/LoginPage.tsx
  packages/storage-ui/src/Components/StorageRoutes.tsx
  packages/storage-ui/src/Contexts/DnDContext.tsx
  packages/storage-ui/src/Contexts/FileBrowserContext.tsx
  packages/storage-ui/src/Contexts/FileOperationsReducers.tsx
  packages/storage-ui/src/Contexts/StorageContext.tsx
  packages/storage-ui/src/Contexts/types.ts
  packages/storage-ui/src/Utils/pathUtils.ts
Labels: Status: Review Needed 👀, Type: Feature

#1154 Bump cypress to v7.5
  packages/files-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: Type: Maintenance

#1078 Shared folder overview
  packages/common-components/src/Icons/icons/UserShare.icon.tsx
  packages/common-components/src/Icons/index.ts
  packages/common-components/src/Icons/svgs/user-share.svg
  packages/files-ui/src/Components/Elements/SharedUser.tsx
  packages/files-ui/src/Components/FilesRoutes.tsx
  packages/files-ui/src/Components/Layouts/AppNav.tsx
  packages/files-ui/src/Components/Modules/DownloadProgressModals/index.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFolderRowWrapper.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/types.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/Utils/pathUtils.ts
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/fr/messages.po
Labels: Type: Feature

#1153 Remove a wait in tests
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/package.json
  packages/files-ui/src/Components/Modules/UploadFileModule.tsx
  yarn.lock
Labels: Status: Review Needed 👀, Type: Bug Fix

#1165 Make cypress tests use chrome version 90 in ci
  .github/workflows/test.yml
  packages/files-ui/package.json
  packages/storage-ui/package.json
Labels: Status: Review Needed 👀, Type: Maintenance

#1160 Update commands.ts to use page object properties
  packages/files-ui/cypress/support/commands.ts
  packages/files-ui/cypress/support/page-objects/authenticationPage.ts
  packages/files-ui/cypress/support/page-objects/basePage.ts
  packages/files-ui/cypress/support/page-objects/landingPage.ts
  packages/files-ui/cypress/tests/main-navigation-spec.ts
Labels: Status: Review Needed 👀, Type: Maintenance

#1181 Cancel editing when there's a click outside
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1179 disable buttons for renaming file/folder
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1178 Disabled button in settings when no change made
  packages/files-ui/src/Components/Modules/Settings/Profile.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1180 Fix lookup and validation
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/Settings/Profile.tsx
  packages/files-ui/src/Contexts/UserContext.tsx
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/fr/messages.po
Labels: Status: Review Needed 👀, Type: Bug Fix

#1166 Add ternary autofix eslint rule and unused vars
  .eslintrc.json
  package.json
  packages/common-components/src/Blockies/Blockies.tsx
  packages/common-components/src/FileInput/FileInput.tsx
  packages/common-components/src/NumberInput/FormikNumberInput.tsx
  packages/common-components/src/Router/ConditionalRoute.tsx
  packages/common-components/src/Spinner/Spinner.tsx
  packages/common-components/src/TextInput/FormikTextInput.tsx
  packages/common-components/src/Typography/Typography.tsx
  packages/common-theme/src/utils/colorManipulator.ts
  packages/files-ui/src/Components/Elements/CustomButton.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/FileInfoModal.tsx
  packages/files-ui/src/Components/Modules/LoginModule/AuthenticationFactors.tsx
  packages/files-ui/src/Components/Modules/LoginModule/MigrateAccount.tsx
  packages/files-ui/src/Components/Modules/Settings/Profile.tsx
  packages/files-ui/src/Components/Pages/LoginPage.tsx
  packages/files-ui/src/Contexts/FilesApiContext.tsx
  packages/storage-ui/src/Components/Elements/CustomButton.tsx
  packages/storage-ui/src/Components/Modules/LoginModule.tsx
  packages/storage-ui/src/Components/Pages/LoginPage.tsx
  packages/storage-ui/src/Contexts/StorageApiContext.tsx
  yarn.lock
Labels: Status: Review Needed 👀, Type: Maintenance

#1193 Fix overflow in Storage api keys, buckets and cid pages
  packages/storage-ui/src/Components/Layouts/AppHeader.tsx
  packages/storage-ui/src/Components/Modules/ApiKeys.tsx
  packages/storage-ui/src/Components/Pages/BucketsPage.tsx
  packages/storage-ui/src/Components/Pages/CidsPage.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1167 Mobile view of shared folders
  packages/files-ui/src/Components/Elements/SharedUser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1169 Fix lgtm alerts
  packages/common-components/src/Modal/Modal.tsx
  packages/common-components/src/NumberInput/NumberInput.tsx
  packages/common-components/src/SearchBar/SearchBar.tsx
  packages/common-components/src/TextInput/TextInput.tsx
  packages/common-theme/src/utils/colorManipulator.ts
  packages/files-ui/cypress/support/index.ts
  packages/files-ui/src/Contexts/ThresholdKeyContext.tsx
Labels: Type: Bug Fix

#1198 Fix lint action for forked repos
  .github/workflows/lint.yml
Labels: Status: Review Needed 👀, Type: Bug Fix

#1195 Setup Storage testing
  .github/workflows/test-files.yml
  .github/workflows/test-storage.yml
  .gitignore
  package.json
  packages/files-ui/package.json
  packages/storage-ui/cypress.json
  packages/storage-ui/cypress/plugins/index.ts
  packages/storage-ui/cypress/support/commands.ts
  packages/storage-ui/cypress/support/page-objects/authenticationPage.ts
  packages/storage-ui/cypress/support/page-objects/basePage.ts
  packages/storage-ui/cypress/support/page-objects/bucketsPage.ts
  packages/storage-ui/cypress/support/page-objects/cidsPage.ts
  packages/storage-ui/cypress/support/page-objects/homePage.ts
  packages/storage-ui/cypress/support/page-objects/navigationMenu.ts
  packages/storage-ui/cypress/support/page-objects/settingsPage.ts
  packages/storage-ui/cypress/support/utils/apiTestHelper.ts
  packages/storage-ui/cypress/tests/main-navigation-spec.ts
  packages/storage-ui/package.json
  packages/storage-ui/src/Components/Layouts/AppHeader.tsx
  packages/storage-ui/src/Components/Layouts/AppNav.tsx
  packages/storage-ui/src/Components/Modules/ApiKeys.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Pages/CidsPage.tsx
Labels: Status: Review Needed 👀, Type: Feature
