Repository ChainSafe/ui-monorepo, pull requests merged in 2021-09, with the labels that each got.

#1477 Sharing feature explainer
  packages/common-components/src/Dialog/Dialog.tsx
  packages/common-components/src/Modal/Modal.tsx
  packages/common-components/src/stories/Modal.stories.tsx
  packages/files-ui/src/App.tsx
  packages/files-ui/src/Components/Elements/CustomModal.tsx
  packages/files-ui/src/Components/Elements/ShareTransferRequestModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareToSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useSharingExplainerModalFlag.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Modules/Settings/SavedBrowsers/BrowserPanel.tsx
  packages/files-ui/src/Components/SharingExplainerModal.tsx
  packages/files-ui/src/Media/sharingExplainer/step1.png
  packages/files-ui/src/Media/sharingExplainer/step2.png
  packages/files-ui/src/Media/sharingExplainer/step3.png
  packages/files-ui/src/Themes/Constants.ts
  packages/files-ui/src/Themes/DarkTheme.ts
  packages/files-ui/src/Themes/LightTheme.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/gaming-ui/src/App.tsx
  packages/storage-ui/src/App.tsx
  packages/storage-ui/src/Components/Elements/CustomModal.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemItem.tsx
Labels: Status: Review Needed 👀, Type: Feature

#1470 Adding multi selects on mobile view with long press
  packages/common-components/src/Table/Table.tsx
  packages/common-theme/src/Hooks/index.ts
  packages/common-theme/src/Hooks/useLongPress.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Themes/Constants.ts
  packages/files-ui/src/Themes/DarkTheme.ts
  packages/files-ui/src/Themes/LightTheme.ts
Labels: Status: Review Needed 👀, Type: Feature

#1493 Bump files-api-client to 1.18.5
  packages/files-ui/package.json
  packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/storage-ui/package.json
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  yarn.lock
Labels: Type: Maintenance, Status: Review Needed 👀

#1487 [Files] - New survey - Discord link and tiny fix
  packages/files-ui/src/Components/FilesRoutes.tsx
  packages/files-ui/src/Components/Layouts/AppNav.tsx
  packages/files-ui/src/Components/Modules/Settings/index.tsx
  packages/files-ui/src/Components/SurveyBanner.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance, Status: Review Needed 👀

#1491 Merge dev into epic/files-billing
  .github/workflows/test-storage.yml
  packages/common-components/src/Dialog/Dialog.tsx
  packages/common-components/src/Modal/Modal.tsx
  packages/common-components/src/SearchBar/SearchBar.tsx
  packages/common-components/src/Table/Table.tsx
  packages/common-components/src/stories/Modal.stories.tsx
  packages/common-theme/src/Hooks/index.ts
  packages/common-theme/src/Hooks/useLongPress.tsx
  packages/files-ui/cypress/fixtures/filesTestData.ts
  packages/files-ui/cypress/support/page-objects/basePage.ts
  packages/files-ui/cypress/support/page-objects/binPage.ts
  packages/files-ui/cypress/support/page-objects/fileBrowser.ts
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/cypress/support/page-objects/searchPage.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/cypress/tests/search-spec.ts
  packages/files-ui/package.json
  packages/files-ui/src/App.tsx
  packages/files-ui/src/Components/Elements/CustomModal.tsx
  packages/files-ui/src/Components/Elements/ShareTransferRequestModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareToSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useSharingExplainerModalFlag.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Modules/SearchModule.tsx
  packages/files-ui/src/Components/Modules/Settings/SecurityTab/SavedBrowsers/BrowserPanel.tsx
  packages/files-ui/src/Components/SharingExplainerModal.tsx
  packages/files-ui/src/Media/sharingExplainer/step1.png
  packages/files-ui/src/Media/sharingExplainer/step2.png
  packages/files-ui/src/Media/sharingExplainer/step3.png
  packages/files-ui/src/Themes/Constants.ts
  packages/files-ui/src/Themes/DarkTheme.ts
  packages/files-ui/src/Themes/LightTheme.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/gaming-ui/package.json
  packages/gaming-ui/src/App.tsx
  packages/storage-ui/package.json
  packages/storage-ui/src/App.tsx
  packages/storage-ui/src/Components/Elements/CustomModal.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/locales/en/messages.po
  yarn.lock
Labels: Status: Review Needed 👀

#1498 update axios
  packages/files-ui/package.json
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/gaming-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: Type: Maintenance, Status: Review Needed 👀

#1497 Added docs link
  packages/common-components/src/Icons/icons/Document.icon.tsx
  packages/common-components/src/Icons/index.ts
  packages/common-components/src/Icons/svgs/document.svg
  packages/storage-ui/src/Components/Layouts/AppNav.tsx
  packages/storage-ui/src/locales/en/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1502 Merge dev into epic/files-billing
  packages/common-components/src/Icons/icons/Document.icon.tsx
  packages/common-components/src/Icons/index.ts
  packages/common-components/src/Icons/svgs/document.svg
  packages/files-ui/package.json
  packages/files-ui/src/Components/FilesRoutes.tsx
  packages/files-ui/src/Components/Layouts/AppNav.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/Settings/index.tsx
  packages/files-ui/src/Components/SurveyBanner.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/gaming-ui/package.json
  packages/storage-ui/package.json
  packages/storage-ui/src/Components/Layouts/AppNav.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/locales/en/messages.po
  yarn.lock
Labels: Type: Maintenance, Status: Review Needed 👀

#1501 Upgrade to remove warning in console
  yarn.lock
Labels: Type: Maintenance, Status: Review Needed 👀

#1503 Published Components & Theme
  packages/common-components/package.json
  packages/common-theme/package.json
Labels: Type: Maintenance

#1489 Add ui tests for file preview
  .gitignore
  packages/files-ui/cypress/fixtures/uploadedFiles/file.zip
  packages/files-ui/cypress/support/page-objects/modals/previewModal.ts
  packages/files-ui/cypress/tests/file-preview-spec.ts
  packages/files-ui/src/Components/Modules/FilePreviewModal.tsx
  packages/files-ui/src/Components/Modules/PreviewRenderers/ImagePreview.tsx
Labels: Type: Maintenance, Status: Review Needed 👀

#1513 Using useRef to keep track of toasts
  packages/common-components/src/Toasts/ToastContext.tsx
Labels: Status: Review Needed 👀

#1495 Toasts refactor
  packages/common-components/.storybook/contexts.js
  packages/common-components/src/Icons/svgs/close-circle.svg
  packages/common-components/src/Icons/svgs/cross.svg
  packages/common-components/src/Toaster/ToastContainer.tsx
  packages/common-components/src/Toaster/Toaster.tsx
  packages/common-components/src/Toaster/ToasterContent.tsx
  packages/common-components/src/Toaster/ToasterProvider.tsx
  packages/common-components/src/Toaster/ToasterWrapper.tsx
  packages/common-components/src/Toaster/index.ts
  packages/common-components/src/Toasts/ToastContent.tsx
  packages/common-components/src/Toasts/ToastContext.tsx
  packages/common-components/src/Toasts/index.ts
  packages/common-components/src/Toasts/types.ts
  packages/common-components/src/index.ts
  packages/common-components/src/stories/Toaster.stories.tsx
  packages/common-components/src/stories/Toasts.stories.tsx
  packages/common-theme/src/Overrides/Toaster.ts
  packages/common-theme/src/Overrides/Toasts.ts
  packages/common-theme/src/Overrides/index.ts
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/src/App.tsx
  packages/files-ui/src/Components/Modules/DownloadProgressToast/DownloadToast.tsx
  packages/files-ui/src/Components/Modules/DownloadProgressToast/index.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SearchFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/types.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Modules/SearchModule.tsx
  packages/files-ui/src/Components/Modules/Settings/Profile.tsx
  packages/files-ui/src/Components/Modules/TransferProgressToast/TransferToast.tsx
  packages/files-ui/src/Components/Modules/TransferProgressToast/index.tsx
  packages/files-ui/src/Components/Modules/UploadProgressToast/UploadToast.tsx
  packages/files-ui/src/Components/Modules/UploadProgressToast/index.tsx
  packages/files-ui/src/Contexts/FileBrowserContext.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/Contexts/FilesReducers.tsx
  packages/files-ui/src/Themes/DarkTheme.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/gaming-ui/src/App.tsx
  packages/gaming-ui/src/Components/Elements/CustomModal.tsx
  packages/gaming-ui/src/Themes/DarkTheme.ts
  packages/storage-ui/src/App.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/Themes/DarkTheme.ts
  yarn.lock
Labels: Status: Review Needed 👀, Type: Feature

#1500 Progress cancellations
  packages/common-components/src/Toasts/ToastContent.tsx
  packages/common-components/src/Toasts/types.ts
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1512 survey banner on safari fix
  packages/files-ui/src/Components/SurveyBanner.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1518 Fix toasts not rendering
  packages/common-components/src/Toasts/ToastContext.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1517 Change the survey to a call for a user interview
  packages/files-ui/src/Components/FilesRoutes.tsx
  packages/files-ui/src/Components/SurveyBanner.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance

#1521 bump cypress to v8.4
  packages/files-ui/package.json
  packages/gaming-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: Type: Maintenance, Status: Review Needed 👀

#1519 Adjusting login screen sizes.
  packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/gaming-ui/src/Components/Modules/LoginModule.tsx
  packages/storage-ui/src/Components/Modules/LoginModule.tsx
Labels: Type: Bug Fix

#1526 bulk recover operation
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
Labels: Type: Feature

#1520 Add new ui tests for illogical folder and file move errors
  packages/files-ui/cypress/tests/file-management-spec.ts
Labels: Type: Maintenance, Status: Review Needed 👀

#1514 Posthog Analytics Integration
  packages/files-ui/package.json
  packages/files-ui/src/App.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Pages/BinPage.tsx
  packages/files-ui/src/Components/Pages/DrivePage.tsx
  packages/files-ui/src/Components/Pages/LoginPage.tsx
  packages/files-ui/src/Components/Pages/SearchPage.tsx
  packages/files-ui/src/Components/Pages/SettingsPage.tsx
  packages/files-ui/src/Components/Pages/SharedFilesPage.tsx
  packages/files-ui/src/Contexts/PosthogContext.tsx
  packages/files-ui/src/index.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  yarn.lock
Labels: Type: Maintenance, Status: Review Needed 👀

#1528 Translations update from Weblate
  packages/files-ui/src/locales/fr/messages.po
Labels: Status: Review Needed 👀

#1527 [Files] - Share to home or other shared folder
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1515 Folder uploads
  packages/common-components/src/FileInput/FileInput.tsx
  packages/files-ui/package.json
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/UploadFileModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/Utils/getFilesFromDataTransferItems.ts
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Modules/UploadFileModal/UploadFileModal.tsx
  yarn.lock
Labels: Status: Review Needed 👀, Type: Feature

#1531 Don't track before opt-in
  packages/files-ui/src/Contexts/PosthogContext.tsx
  packages/files-ui/src/index.tsx
  packages/files-ui/src/locales/fr/messages.po
Labels: Type: Bug Fix, Status: Review Needed 👀

#1534 [Files] - Show current bucket decryption key
  packages/files-ui/src/Components/Modules/FileBrowsers/FileInfoModal.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1485 [Files] - Get admin public key from the api
  packages/files-ui/src/Components/Modules/FileBrowsers/ReportFileModal.tsx
Labels: Type: Maintenance, Status: Review Needed 👀

#1535 Add lint rules for test debug commands
  .eslintrc.json
  package.json
  yarn.lock
Labels: Type: Maintenance

#1538 Prevent double opening of the file picker
  packages/common-components/src/FileInput/FileInput.tsx
Labels: Type: Bug Fix

#1539 Add ui tests for deleting and recovering multiple files
  packages/common-components/src/CheckboxInput/CheckboxInput.tsx
  packages/files-ui/cypress/support/page-objects/binPage.ts
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
Labels: Type: Maintenance, Status: Review Needed 👀

#1536 Add test coverage for storage summary adjustments
  packages/common-components/src/CheckboxInput/CheckboxInput.tsx
  packages/files-ui/cypress/support/page-objects/binPage.ts
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/cypress/support/page-objects/navigationMenu.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/cypress/tests/main-navigation-spec.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
Labels: Type: Maintenance, Status: Review Needed 👀

#1550 Better colors for dark mode select and tagsinput components
  packages/common-components/src/SelectInput/SelectInput.tsx
  packages/files-ui/src/Themes/DarkTheme.ts
  packages/files-ui/src/locales/fr/messages.po
Labels: Type: Bug Fix, Status: Review Needed 👀

#1548 Filter out current bucket
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1555 [Files] - fix cookie banner colors in dark mode
  packages/files-ui/src/Contexts/PosthogContext.tsx
  packages/files-ui/src/Themes/Constants.ts
  packages/files-ui/src/Themes/DarkTheme.ts
  packages/files-ui/src/Themes/LightTheme.ts
Labels: Type: Bug Fix, Status: Review Needed 👀

#1553 Fix user lookup spamming the api, and throwing
  packages/common-components/src/TagsInput/TagsInput.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useLookupUser.tsx
  packages/files-ui/src/Components/Modules/Settings/Profile.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Bug Fix, Status: Review Needed 👀

#1549 Upgrade Torus dependencies
  .github/workflows/test-storage.yml
  packages/files-ui/package.json
  packages/files-ui/src/Contexts/ThresholdKeyContext.tsx
  packages/gaming-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: Type: Bug Fix

#1577 [Files] - Reset fields on shared folders modals
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useLookupUser.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1578 Reset forms and fix a couple error types
  packages/common-components/src/TextInput/TextInput.tsx
  packages/files-ui/src/Components/Elements/PasswordForm.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateFolderModal.tsx
  packages/files-ui/src/Components/Modules/LoginModule/PasswordlessEmail.tsx
  packages/files-ui/src/Components/Modules/Settings/PurchasePlan/index.tsx
  packages/files-ui/src/Contexts/UserContext.tsx
  packages/storage-ui/src/Components/Modules/CreateFolderModal/CreateFolderModal.tsx
  packages/storage-ui/src/Components/Modules/UploadFileModal/UploadFileModal.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1557 Translations update from Weblate
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/fr/messages.po
Labels: Type: Maintenance

#1576 Hide menu when there's no menu item
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1581 Add "maintenance" label to weblate PRs automatically
  .github/pr-labeler.yml
Labels: Type: Maintenance, Status: Review Needed 👀

#1582 Upgrade api client and fix issue with shared folder renaming
  packages/files-ui/package.json
  packages/files-ui/src/Components/Elements/SharedUsers.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/gaming-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: Type: Bug Fix, Status: Review Needed 👀

#1585 Run lint --fix with "@typescript-eslint/indent": ["error", 2],
  .eslintrc.json
  packages/common-components/src/Icons/types.d.ts
  packages/common-components/src/MenuDropdown/MenuDropdown.tsx
  packages/common-components/src/Typography/Typography.tsx
  packages/common-components/src/stories/Typography.stories.tsx
  packages/common-theme/src/Create/CreateBreakpoints.ts
  packages/common-theme/src/Hooks/useDoubleClick.ts
  packages/files-ui/src/Components/Elements/MnemonicForm.tsx
  packages/files-ui/src/Components/Elements/ShareTransferRequestModal.tsx
  packages/files-ui/src/Components/Elements/SharedUsers.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Modules/LoginModule/InitializeAccount.tsx
  packages/files-ui/src/Components/SharingExplainerModal.tsx
  packages/files-ui/src/Components/SurveyBanner.tsx
  packages/files-ui/src/Contexts/FilesApiContext.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/Contexts/ThresholdKeyContext.tsx
  packages/files-ui/src/Themes/Constants.ts
  packages/files-ui/src/UI-components/Menu.tsx
  packages/files-ui/src/Utils/MimeMatcher.ts
  packages/files-ui/src/Utils/contentTypeGuesser.ts
  packages/gaming-ui/src/Components/Elements/SecretField.tsx
  packages/gaming-ui/src/Contexts/GamingApiContext.tsx
  packages/gaming-ui/src/Themes/Constants.ts
  packages/storage-ui/src/Components/Elements/CidRow.tsx
  packages/storage-ui/src/Components/Elements/SecretField.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Modules/SurveyBanner.tsx
  packages/storage-ui/src/Components/Pages/CidsPage.tsx
  packages/storage-ui/src/Contexts/FileOperationsReducers.tsx
  packages/storage-ui/src/Contexts/StorageApiContext.tsx
  packages/storage-ui/src/Themes/Constants.ts
  packages/storage-ui/src/Utils/MimeMatcher.ts
  packages/storage-ui/src/Utils/contentTypeGuesser.ts
Labels: Type: Bug Fix, Status: Review Needed 👀

#1587 Add team feature fake door
  packages/files-ui/src/Components/Elements/TeamModal.tsx
  packages/files-ui/src/Components/FilesRoutes.tsx
  packages/files-ui/src/Components/Layouts/AppHeader.tsx
  packages/files-ui/src/Contexts/PosthogContext.tsx
Labels: Status: Review Needed 👀, Type: Feature

#1575 Gaming dashboard - API keys as cards
  packages/common-components/src/index.ts
  packages/gaming-ui/src/Components/Elements/ApiKeyCard.tsx
  packages/gaming-ui/src/Components/GamingRoutes.tsx
  packages/gaming-ui/src/Components/Layouts/AppNav.tsx
  packages/gaming-ui/src/Components/Modules/DashboardModule.tsx
  packages/gaming-ui/src/Components/Pages/DashboardPage.tsx
  packages/gaming-ui/src/Components/Pages/SettingsPage.tsx
  packages/gaming-ui/src/locales/en/messages.po
  packages/storage-ui/src/Components/Modules/ApiKeys.tsx
Labels: Status: Review Needed 👀, Type: Feature, Product: Gaming

#1574 New navigations buttons
  packages/common-components/src/Button/Button.tsx
  packages/common-theme/src/Defaults/ThemeConfig.ts
  packages/files-ui/src/Components/Elements/TeamModal.tsx
  packages/files-ui/src/Components/FilesRoutes.tsx
  packages/files-ui/src/Components/Layouts/AppHeader.tsx
  packages/files-ui/src/Components/Layouts/AppNav.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1592 Fix tertiary buttons in dark mode
  packages/common-components/src/Button/Button.tsx
  packages/common-components/src/stories/Button.stories.tsx
  packages/common-theme/src/Overrides/Button.ts
  packages/files-ui/src/Themes/DarkTheme.ts
Labels: Type: Bug Fix, Status: Review Needed 👀

#1590 Posthog identify user on login
  packages/files-ui/src/Contexts/PosthogContext.tsx
Labels: Type: Feature

#1589 Account Restricted
  packages/files-ui/src/Components/Elements/RestrictedModeBanner.tsx
  packages/files-ui/src/Components/Layouts/AppWrapper.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Contexts/FilesApiContext.tsx
  packages/files-ui/src/Themes/Constants.ts
  packages/files-ui/src/UI-components/Menu.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1597 Show username if known for the owner
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1598 Always show a toast close button
  packages/common-components/src/Toasts/ToastContent.tsx
Labels: Type: Maintenance, Status: Review Needed 👀

#1596 Mv and rm batch calls
  packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Utils/pathUtils.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature
