Repository ChainSafe/ui-monorepo, pull requests merged in 2021-08, with the labels that each got.

#1353 create and edit shared folder modals merge
  packages/files-ui/src/Components/Modules/FileBrowsers/CopyToSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useCreateOrEditSharedFolder.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useCreateSharedFolder.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useLookupUser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/types.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Product: Files, Status: Review Needed 👀, Type: Maintenance

#1385 Allow recovering without any folder
  packages/files-ui/src/Components/Modules/FileBrowsers/MoveFileModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Modules/MoveFileModal/MoveFileModal.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1384 update bnc-onboard to 1.32.0
  packages/files-ui/package.json
  packages/gaming-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: Status: Review Needed 👀, Type: Bug Fix

#1386 Upgarde to cypress v8.1
  packages/files-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: Status: Review Needed 👀, Type: Maintenance

#1389 Fix lgtm-bot alerts
  packages/gaming-ui/cypress/support/index.ts
  packages/gaming-ui/cypress/support/utils/apiTestHelper.ts
  packages/storage-ui/cypress/support/index.ts
Labels: Type: Maintenance

#1391 Fix reloading the loader and other components on sharing
  packages/files-ui/src/Components/Modules/FileBrowsers/CopyToSharedFolderModal.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1395 Fix test with onboard bump
  packages/files-ui/cypress/support/commands.ts
  packages/files-ui/cypress/support/page-objects/authenticationPage.ts
  packages/files-ui/package.json
  packages/files-ui/src/App.tsx
  packages/gaming-ui/package.json
  packages/storage-ui/cypress/support/commands.ts
  packages/storage-ui/cypress/support/page-objects/authenticationPage.ts
  packages/storage-ui/package.json
  packages/storage-ui/src/App.tsx
  yarn.lock
Labels: Status: Review Needed 👀, Type: Bug Fix

#1394 Adding buckets user logic
  packages/files-ui/package.json
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/storage-ui/package.json
  yarn.lock
Labels: Status: Review Needed 👀, Type: Feature

#1403 [FILES] Fix preview in search results
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useGetFile.tsx
  packages/files-ui/src/Components/Modules/FilePreviewModal.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1400 breadcrumbs removed from settings: storage
  packages/storage-ui/src/Components/Pages/SettingsPage.tsx
Labels: Type: Maintenance

#1398 Summary size on base 2
  packages/files-ui/src/Components/Layouts/AppNav.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/FileInfoModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/Components/Modules/Settings/Plan.tsx
  packages/gaming-ui/src/Components/Layouts/AppNav.tsx
  packages/storage-ui/src/Components/Elements/BucketRow.tsx
  packages/storage-ui/src/Components/Elements/CidRow.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
Labels: Type: Bug Fix

#1388 Show users at the top of shared folders browser
  packages/files-ui/src/Components/Elements/SharedUser.tsx
  packages/files-ui/src/Components/Elements/SharedUsers.tsx
  packages/files-ui/src/Components/Elements/UserBubble.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Utils/getUserDisplayName.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1402 run chrome headless in ci
  packages/files-ui/package.json
  packages/gaming-ui/package.json
  packages/storage-ui/package.json
Labels: Status: Review Needed 👀, Type: Maintenance

#1401 New auth flow
  packages/files-ui/src/Components/Modules/LoginModule/AuthenticationFactors.tsx
  packages/files-ui/src/Components/Modules/LoginModule/Complete.tsx
  packages/files-ui/src/Components/Modules/LoginModule/ConfirmSkip.tsx
  packages/files-ui/src/Components/Modules/LoginModule/InitializeAccount.tsx
  packages/files-ui/src/Components/Modules/LoginModule/MigrateAccount.tsx
  packages/files-ui/src/Components/Modules/LoginModule/SaveBackupPhrase.tsx
  packages/files-ui/src/Components/Modules/Settings/Security/index.tsx
  packages/files-ui/src/Components/Pages/LoginPage.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Maintenance

#1396 Copy/Move to shared folder
  packages/common-components/src/TagsInput/TagsInput.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareToSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Contexts/FileBrowserContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Feature

#1390 Add validation for new shared folder
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareToSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useCreateOrEditSharedFolder.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
  packages/files-ui/src/Components/Modules/LoginModule/PasswordlessEmail.tsx
  packages/files-ui/src/Utils/validationSchema.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/gaming-ui/src/Components/Modules/LoginModule/PasswordlessEmail.tsx
  packages/storage-ui/src/Components/Modules/AddCIDModal.tsx
  packages/storage-ui/src/Components/Modules/CreateFolderModal/CreateFolderModal.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemGridItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
  packages/storage-ui/src/Components/Modules/LoginModule/PasswordlessEmail.tsx
  packages/storage-ui/src/Utils/validationSchema.ts
  packages/storage-ui/src/locales/en/messages.po
Labels: Status: Review Needed 👀, Type: Bug Fix

#1406 Fix reload of input component
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareToSharedFolderModal.tsx
Labels: Status: Review Needed 👀, Type: Bug Fix

#1407 [FILES] Ensure content type is retained when sharing
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareToSharedFolderModal.tsx
  packages/files-ui/src/Utils/contentTypeGuesser.ts
Labels: Status: Review Needed 👀, Type: Bug Fix

#1383 Add new ui tests for folder creation and deletion
  packages/files-ui/cypress/fixtures/filesTestData.ts
  packages/files-ui/cypress/support/commands.ts
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/storage-ui/cypress/support/commands.ts
Labels: Type: Maintenance

#1417 Bump cypress to v8.2
  packages/files-ui/package.json
  packages/gaming-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: Status: Review Needed 👀, Type: Maintenance

#1413 Update the docker container used for tests to the latest version
  .github/workflows/test-files.yml
  packages/files-ui/cypress/tests/file-management-spec.ts
Labels: Status: Review Needed 👀, Type: Maintenance

#1416 Folder creation validation and test
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateFolderModal.tsx
Labels: Type: Maintenance, Status: Review Needed 👀

#1411 Using default cursors
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemGridItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
Labels: Type: Maintenance, Status: Review Needed 👀

#1423 [Storage] add CID to bucket item row
  packages/storage-ui/src/Components/Elements/CidRow.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Pages/CidsPage.tsx
Labels: Status: Review Needed 👀, Type: Feature

#1421 Use cypress session instead of locally stored files.
  packages/files-ui/cypress.json
  packages/files-ui/cypress/plugins/index.ts
  packages/files-ui/cypress/support/commands.ts
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/cypress/tests/main-navigation-spec.ts
  packages/files-ui/cypress/tests/settings-spec.ts
Labels: Type: Maintenance, Status: Review Needed 👀

#1426 Expose decryption key
  packages/common-components/src/Icons/svgs/eye-closed.svg
  packages/common-components/src/Icons/svgs/eye-open.svg
  packages/common-components/src/ToggleHiddenText/ToggleHiddenText.tsx
  packages/common-components/src/ToggleHiddenText/index.ts
  packages/common-components/src/index.ts
  packages/common-theme/src/Overrides/ToggleHiddenText.ts
  packages/common-theme/src/Overrides/index.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/FileInfoModal.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/Themes/DarkTheme.ts
  packages/files-ui/src/Themes/LightTheme.ts
Labels: Status: Review Needed 👀, Type: Feature

#1427 [Storage] Adapt the email login from like done on Files
  packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
  packages/storage-ui/src/Components/Modules/LoginModule.tsx
  packages/storage-ui/src/Components/Modules/LoginModule/PasswordlessEmail.tsx
  packages/storage-ui/src/Utils/validationSchema.ts
  packages/storage-ui/src/locales/en/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1424 Storage: Download functionality on bucket files
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/Contexts/StorageContext.tsx
Labels: Status: Review Needed 👀, Type: Feature

#1425 Fix lingui failing for weblate PRs
  .github/workflows/lingui-extract-files.yml
  .github/workflows/lingui-extract-gaming.yml
  .github/workflows/lingui-extract-storage.yml
  packages/files-ui/src/Components/Elements/MnemonicForm.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1444 Skip the entire lingui job if the author is weblate
  .github/workflows/lingui-extract-files.yml
  .github/workflows/lingui-extract-gaming.yml
  .github/workflows/lingui-extract-storage.yml
Labels: Type: Bug Fix, Status: Review Needed 👀

#1438 Disabled select on row names & enhance simple click experience
  packages/common-theme/src/Hooks/useDoubleClick.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1439 Define modals in the test suite as separate objects
  packages/files-ui/cypress/support/page-objects/binPage.ts
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/cypress/support/page-objects/modals/createFolderModal.ts
  packages/files-ui/cypress/support/page-objects/modals/deleteFileModal.ts
  packages/files-ui/cypress/support/page-objects/modals/fileUploadModal.ts
  packages/files-ui/cypress/support/page-objects/modals/recoverFileModal.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
Labels: Type: Maintenance, Status: Review Needed 👀

#1182 Billing plan page UI
  packages/common-components/src/Icons/icons/SubscriptionPlan.icon.tsx
  packages/common-components/src/Icons/index.ts
  packages/common-components/src/Icons/svgs/profile.svg
  packages/common-components/src/Icons/svgs/subscription-plan.svg
  packages/files-ui/src/Components/FilesRoutes.tsx
  packages/files-ui/src/Components/Modules/Settings/Plan.tsx
  packages/files-ui/src/Components/Modules/Settings/Products/ProductInfo.tsx
  packages/files-ui/src/Components/Modules/Settings/Products/Products.tsx
  packages/files-ui/src/Components/Modules/Settings/Profile/LanguageSelection.tsx
  packages/files-ui/src/Components/Modules/Settings/Profile/index.tsx
  packages/files-ui/src/Components/Modules/Settings/Security/SavedBrowsers/BrowserPanel.tsx
  packages/files-ui/src/Components/Modules/Settings/Security/SavedBrowsers/index.tsx
  packages/files-ui/src/Components/Modules/Settings/Security/index.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionPlan/CurrentProduct.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionPlan/index.tsx
  packages/files-ui/src/Components/Modules/Settings/index.tsx
  packages/files-ui/src/Components/Pages/PlansPage.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.mo
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/gaming-ui/src/Components/GamingRoutes.tsx
  packages/gaming-ui/src/Components/Layouts/AppHeader.tsx
  packages/gaming-ui/src/Components/Layouts/AppNav.tsx
  packages/gaming-ui/src/Components/Modules/Login/PasswordlessEmail.tsx
  packages/gaming-ui/src/Components/Modules/Login/index.tsx
  packages/gaming-ui/src/Components/Modules/Products/ProductInfo.tsx
  packages/gaming-ui/src/Components/Modules/Products/index.tsx
  packages/gaming-ui/src/Components/Pages/BillingPage.tsx
  packages/gaming-ui/src/Components/Pages/LoginPage.tsx
  packages/gaming-ui/src/Contexts/GamingApiContext.tsx
  packages/gaming-ui/src/locales/en/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1433 Updates to storage ui test suite
  package.json
  packages/files-ui/cypress/support/commands.ts
  packages/files-ui/src/locales/fr/messages.po
  packages/storage-ui/cypress.json
  packages/storage-ui/cypress/plugins/index.ts
  packages/storage-ui/cypress/support/commands.ts
  packages/storage-ui/cypress/support/page-objects/authenticationPage.ts
  packages/storage-ui/cypress/support/page-objects/bucketsPage.ts
  packages/storage-ui/cypress/tests/bucket-management-spec.ts
  packages/storage-ui/cypress/tests/cid-management-spec.ts
  packages/storage-ui/package.json
  packages/storage-ui/src/Components/Elements/BucketRow.tsx
  yarn.lock
Labels: Status: Review Needed 👀

#1452 bump cypress to v8.3
  packages/files-ui/package.json
  packages/gaming-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: Type: Maintenance, Status: Review Needed 👀

#1450 Refresh by navigating to the bin to fix tests
  packages/files-ui/cypress/support/commands.ts
Labels: Type: Bug Fix, Status: Review Needed 👀

#1432 Use material menus
  packages/common-components/src/MenuDropdown/MenuDropdown.tsx
  packages/files-ui/cypress/support/page-objects/basePage.ts
  packages/files-ui/cypress/support/page-objects/binPage.ts
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/package.json
  packages/files-ui/src/Components/Modules/FileBrowsers/views/DragPreviewLayer.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Modules/FilePreviewModal.tsx
  packages/files-ui/src/Themes/Constants.ts
  packages/files-ui/src/Themes/DarkTheme.ts
  packages/files-ui/src/Themes/LightTheme.ts
  packages/files-ui/src/UI-components/Menu.tsx
  yarn.lock
Labels: Type: Bug Fix, Status: Review Needed 👀

#1451 Extend ui tests coverage to include file moving and permanent deletion
  packages/files-ui/cypress/support/commands.ts
  packages/files-ui/cypress/support/page-objects/modals/moveItemModal.ts
  packages/files-ui/cypress/support/page-objects/modals/recoverItemModal.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
Labels: Type: Maintenance, Status: Review Needed 👀

#1441 Unblock UI while sharing
  packages/files-ui/src/Components/Modules/DownloadProgressToast/DownloadToast.tsx
  packages/files-ui/src/Components/Modules/DownloadProgressToast/index.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareToSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Modules/TransferProgressToast/TransferToast.tsx
  packages/files-ui/src/Components/Modules/TransferProgressToast/index.tsx
  packages/files-ui/src/Components/Modules/UploadFileModule.tsx
  packages/files-ui/src/Components/Modules/UploadProgressToast/UploadToast.tsx
  packages/files-ui/src/Components/Modules/UploadProgressToast/index.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/Contexts/FilesReducers.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1461 Remove pause command from test layer
  packages/files-ui/cypress/tests/file-management-spec.ts
Labels: Type: Maintenance, Status: Review Needed 👀

#1446 billing - Add card
  packages/common-components/src/Tabs/Tabs.tsx
  packages/files-ui/package.json
  packages/files-ui/src/Components/Elements/CardInputs/index.tsx
  packages/files-ui/src/Components/Elements/CardInputs/utils/formatter.ts
  packages/files-ui/src/Components/Elements/CardInputs/utils/validator.ts
  packages/files-ui/src/Components/FilesRoutes.tsx
  packages/files-ui/src/Components/Modules/Settings/Products/Products.tsx
  packages/files-ui/src/Components/Modules/Settings/PurchasePlan/countryList.ts
  packages/files-ui/src/Components/Modules/Settings/PurchasePlan/index.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionPlan/AddCardModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionPlan/CurrentProduct.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionPlan/index.tsx
  packages/files-ui/src/Components/Modules/Settings/index.tsx
  packages/files-ui/src/Components/Pages/PurchasePlanPage.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  yarn.lock
Labels: Status: Review Needed 👀, Type: Feature

#1464 [FILES] enforce maximum 32 char limit
  packages/files-ui/src/Components/Modules/Settings/Profile.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Bug Fix, Status: Review Needed 👀

#1462 Implement cypress retry mechanism
  packages/files-ui/cypress.json
Labels: Type: Maintenance, Status: Review Needed 👀

#1459 [Files] Download multiple files in a zip
  packages/files-ui/package.json
  packages/files-ui/src/Components/Modules/DownloadProgressToast/DownloadToast.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useGetFile.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Modules/TransferProgressToast/TransferToast.tsx
  packages/files-ui/src/Components/Modules/UploadProgressToast/UploadToast.tsx
  packages/files-ui/src/Components/Pages/LoginPage.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/Contexts/FilesReducers.tsx
  packages/files-ui/src/Utils/pathUtils.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  yarn.lock
Labels: Status: Review Needed 👀, Type: Feature

#1430 Programmatic folder creation for tests
  packages/common-components/src/Table/Table.tsx
  packages/files-ui/cypress/fixtures/filesTestData.ts
  packages/files-ui/cypress/support/commands.ts
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/cypress/support/utils/apiTestHelper.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/package.json
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
Labels: Status: Review Needed 👀, Type: Feature

#1469 Add debug and change timeout strategy for tests
  .github/workflows/test-files.yml
Labels: Type: Bug Fix, Status: Review Needed 👀

#1437 [Storage] Copy cid functionality
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
Labels: Type: Bug Fix

#1463 Current card: billing
  packages/common-components/src/Icons/icons/CreditCard.icon.tsx
  packages/common-components/src/Icons/index.ts
  packages/common-components/src/Icons/svgs/credit-card.svg
  packages/files-ui/package.json
  packages/files-ui/src/Components/Modules/Settings/SubscriptionPlan/AddCardModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionPlan/CurrentCard.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionPlan/index.tsx
  packages/files-ui/src/Contexts/BillingContext.tsx
  yarn.lock
Labels: Type: Feature

#1472 10min timeout for everyone
  .github/workflows/test-files.yml
  .github/workflows/test-storage.yml
Labels: Type: Bug Fix, Status: Review Needed 👀

#1476 [FILES] Subscription tab update
  packages/files-ui/src/Components/Modules/Settings/ProfileTab/LanguageSelection.tsx
  packages/files-ui/src/Components/Modules/Settings/ProfileTab/index.tsx
  packages/files-ui/src/Components/Modules/Settings/SecurityTab/SavedBrowsers/BrowserPanel.tsx
  packages/files-ui/src/Components/Modules/Settings/SecurityTab/SavedBrowsers/index.tsx
  packages/files-ui/src/Components/Modules/Settings/SecurityTab/index.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionPlan/CurrentCard.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionPlan/index.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCardModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentCard.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentProduct.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/index.tsx
  packages/files-ui/src/Components/Modules/Settings/index.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1479 add ui tests for search
  packages/common-components/src/SearchBar/SearchBar.tsx
  packages/files-ui/cypress/fixtures/filesTestData.ts
  packages/files-ui/cypress/support/page-objects/basePage.ts
  packages/files-ui/cypress/support/page-objects/binPage.ts
  packages/files-ui/cypress/support/page-objects/fileBrowser.ts
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/cypress/support/page-objects/searchPage.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/cypress/tests/search-spec.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Modules/SearchModule.tsx
  packages/files-ui/src/locales/fr/messages.po
Labels: Type: Maintenance, Status: Review Needed 👀

#1480 bump cypress to v8.3.1
  packages/files-ui/package.json
  packages/gaming-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: Type: Maintenance, Status: Review Needed 👀
