Repository ChainSafe/ui-monorepo, pull requests merged in 2021-11, with the labels that each got.

#1677 [Files] Fix home page and nav menu display issues on smaller screens
  packages/files-ui/src/Components/Layouts/AppNav.tsx
  packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
  packages/files-ui/src/Components/Pages/LoginPage.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1689 Remove scrollbar from the nav bar
  packages/files-ui/src/Components/Layouts/AppNav.tsx
Labels: Type: Bug Fix

#1686 Translations update from Weblate
  packages/files-ui/src/locales/fr/messages.po
Labels: Type: Maintenance

#1676 Fix mobile search showing up when clicking the header
  packages/files-ui/src/Components/Layouts/AppHeader.tsx
  packages/files-ui/src/Components/Modules/SearchModule.tsx
  packages/files-ui/src/locales/fr/messages.po
Labels: Type: Bug Fix

#1674 [Files] Verfy a sharing link asap and give nice error
  packages/files-ui/package.json
  packages/files-ui/src/Components/Modules/LinkSharingModule.tsx
  packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
  packages/files-ui/src/Utils/pathUtils.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/gaming-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: Status: Review Needed 👀, Type: Feature

#1691 Add basic file sharing ui tests
  packages/files-ui/cypress/fixtures/filesTestData.ts
  packages/files-ui/cypress/support/commands.ts
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/cypress/support/page-objects/modals/createSharedFolderModal.ts
  packages/files-ui/cypress/support/page-objects/modals/deleteSharedFolderModal.ts
  packages/files-ui/cypress/support/page-objects/sharedPage.ts
  packages/files-ui/cypress/support/utils/apiTestHelper.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/cypress/tests/file-sharing-spec.ts
  packages/files-ui/cypress/tests/sharing-explainer-spec.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
Labels: Type: Maintenance

#1693 Show a loader for shared folder, and an error if the user doesn't have access to it
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Bug Fix, Status: Review Needed 👀

#1697 Translations update from Weblate
  packages/files-ui/src/locales/fr/messages.po
Labels: Type: Maintenance

#1703 Improve reliability of file moving test
  packages/files-ui/cypress/support/page-objects/basePage.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/src/locales/fr/messages.po
Labels: Type: Maintenance

#1702 add new workflow for ui tests on demand
  .github/workflows/test-files-on-demand.yml
Labels: Type: Maintenance

#1492 [Files] - Billing history
  packages/files-ui/src/Components/FilesRoutes.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentCard.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/index.tsx
  packages/files-ui/src/Components/Modules/Settings/index.tsx
  packages/files-ui/src/Components/Pages/BillingHistory.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1709 Fix Safari Nav Items invisible
  packages/files-ui/src/Components/Layouts/AppNav.tsx
Labels: Type: Bug Fix

#1710 Tweak config of slack notifier
  .github/workflows/test-files-on-demand.yml
Labels: Type: Maintenance

#1711 Added scroll to nav menu
  packages/files-ui/src/Components/Layouts/AppNav.tsx
Labels: Type: Bug Fix

#1713 CID cutoff fix
  packages/files-ui/src/Components/Modules/FileBrowsers/FileInfoModal.tsx
  packages/files-ui/src/locales/fr/messages.po
Labels: Type: Bug Fix, Status: Review Needed 👀

#1712 Header buttons and icons alignments
  packages/files-ui/src/Components/Elements/SharedUsers.tsx
  packages/files-ui/src/Components/Elements/UserBubble.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Bug Fix, Status: Review Needed 👀

#1717 fix cancel download, content not clearing, search preview content type
  packages/files-ui/src/Components/Modules/FileBrowsers/SearchFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FilePreviewModal.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
Labels: Type: Bug Fix

#1723 Trim email nonce submition
  packages/files-ui/src/Components/Modules/LoginModule/PasswordlessEmail.tsx
  packages/gaming-ui/src/Components/Modules/LoginModule/PasswordlessEmail.tsx
  packages/storage-ui/src/Components/Modules/LoginModule/PasswordlessEmail.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1715 Add second section for modals and move away from absolute positionning
  packages/common-components/src/Dialog/Dialog.tsx
  packages/common-components/src/Modal/Modal.tsx
  packages/common-theme/src/Defaults/ThemeConfig.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/FileInfoModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/MoveFileModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ReportFileModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
Labels: Type: Bug Fix

#1719 Adding dynamic positioning to menu drop down
  packages/common-components/src/MenuDropdown/MenuDropdown.tsx
  packages/common-components/src/Scroll/index.ts
  packages/common-components/src/Scroll/useOnScroll.hook.tsx
Labels: Type: Bug Fix

#1735 Fix close button at the wrong place
  packages/files-ui/src/Components/SharingExplainerModal.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1730 Added blockers
  packages/files-ui/src/Components/Layouts/AppNav.tsx
Labels: Type: Bug Fix

#1705 Changed mobile click sensitivity
  packages/common-components/src/Table/TableCell.tsx
  packages/common-theme/src/Hooks/useLongPress.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1737 User lookup consent
  packages/common-theme/src/Hooks/useLongPress.tsx
  packages/files-ui/package.json
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useLookupUser.tsx
  packages/files-ui/src/Components/Modules/Settings/Profile.tsx
  packages/files-ui/src/Contexts/UserContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/gaming-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: Type: Feature

#1732 Disabled auto focus safari
  packages/files-ui/public/index.html
Labels: Type: Bug Fix

#1740 Preview Hotkeys work consistently
  packages/files-ui/src/Components/Modules/FilePreviewModal.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1738 Fix Preview loading if interrupted
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useGetFile.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
Labels: Type: Bug Fix

#1751 add template for pull requests
  .github/ISSUE_TEMPLATE/pull_request_template.md
Labels: Type: Maintenance

#1749 bump cypress to v9.0
  packages/files-ui/package.json
  packages/gaming-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: dependencies

#1722 Link sharing redesign
  packages/files-ui/src/Components/Elements/MnemonicForm.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/LinkList.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/SharingLink.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Bug Fix, Status: Review Needed 👀

#1731 Fixed placeholder spacing
  packages/common-theme/src/Provider/ThemeSwitcherContext.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx
Labels: Type: Bug Fix

#1756 Add subdirectory for pr template
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
Labels: Type: Maintenance

#1755 Add ui test for hotkey navigation in file preview
  packages/files-ui/cypress/fixtures/uploadedFiles/chainsafe.png
  packages/files-ui/cypress/tests/file-preview-spec.ts
Labels: Type: Maintenance

#1752 Fix video preview overflow
  packages/files-ui/src/Components/Modules/PreviewRenderers/VideoPreview.tsx
Labels: Type: Bug Fix

#1736 Share files from browser support
  packages/common-components/src/Button/Button.tsx
  packages/common-components/src/CheckboxInput/CheckboxInput.tsx
  packages/common-components/src/Modal/Modal.tsx
  packages/common-components/src/SelectInput/SelectInput.tsx
  packages/common-components/src/stories/Button.stories.tsx
  packages/common-theme/src/Overrides/Button.ts
  packages/files-ui/src/Components/Elements/CustomModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrManageSharedFolder.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrManageSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Contexts/PosthogContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Feature

#1759 Revert Clipboard changes
  packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/SharingLink.tsx
Labels: Type: Maintenance

#1766 Report modal styles and cut off fix
  packages/files-ui/src/Components/Modules/FileBrowsers/ReportFileModal.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1768 Fix Mobile Nav Drawer blocks breadcrumb
  packages/files-ui/src/Components/Layouts/AppNav.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1769 Link hover colors for secondary button
  packages/common-components/src/Button/Button.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1773 File info modal CID and Key copy arrangements
  packages/files-ui/src/Components/Modules/FileBrowsers/FileInfoModal.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Bug Fix

#1774 fix share transfer modal alignment
  packages/files-ui/src/Components/Elements/ShareTransferRequestModal.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1776 Move pr template to .github root dir
  .github/PULL_REQUEST_TEMPLATE/pull_request_template.md
  .github/pull_request_template.md
Labels: Type: Maintenance

#1778 resolve double tap
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1779 Mobile sharing folder rename modal
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Bug Fix

#1760 Rename with split extension
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
Labels: Type: Feature

#1775 Add ui test coverage for link creation / deletion
  packages/files-ui/cypress/support/index.ts
  packages/files-ui/cypress/support/page-objects/modals/createSharedFolderModal.ts
  packages/files-ui/cypress/support/page-objects/sharedPage.ts
  packages/files-ui/cypress/tests/link-sharing-spec.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/LinkList.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/LinkSharing/SharingLink.tsx
Labels: Type: Maintenance

#1785 Bump Cypress to 9.1
  packages/files-ui/package.json
  packages/files-ui/src/locales/fr/messages.po
  packages/gaming-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: Type: Maintenance, Status: Review Needed 👀
