Repository ChainSafe/ui-monorepo, pull requests merged in 2022-02, with the labels that each got.

#1896 No search results response handle
  packages/files-ui/src/Components/Modules/FileBrowsers/SearchFileBrowser.tsx
  packages/files-ui/src/Components/Modules/SearchModule.tsx
Labels: Type: Maintenance

#1901 Fix margin for theme boxes
  packages/files-ui/src/Components/Modules/Settings/ProfileTab/index.tsx
Labels: Type: Bug Fix

#1902 Remove general modal buttons when adding/updating a card
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/PaymentMethodSelector.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/AddCard.tsx
Labels: Type: Bug Fix

#1890 Add mobile notifications and adapt its design
  packages/common-components/src/MenuDropdown/MenuDropdown.tsx
  packages/files-ui/src/Components/Elements/Notifications/NotificationLine.tsx
  packages/files-ui/src/Components/Elements/Notifications/NotificationList.tsx
  packages/files-ui/src/Components/Elements/Notifications/NotificationsDropdown.tsx
  packages/files-ui/src/Components/Layouts/AppHeader.tsx
  packages/files-ui/src/Components/Modules/SearchModule.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance

#1903 Fix time left in crypto payment
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/CryptoPayment.tsx
Labels: Type: Bug Fix

#1906 Card subscriptions and billing page design
  packages/common-components/src/ProgressBar/ProgressBar.tsx
  packages/files-ui/src/Components/Elements/InvoiceLines.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentCard.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentPlan.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/index.tsx
  packages/files-ui/src/Themes/Constants.ts
  packages/files-ui/src/Themes/DarkTheme.ts
  packages/files-ui/src/Themes/LightTheme.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance

#1915 Store monthly/yearly state higher in the arch tree and remember it
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/PlanDetails.tsx
Labels: Type: Bug Fix

#1916 fix design nit
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Bug Fix

#1917 Add warning before proceeding to crypto payment
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/ConfirmPlan.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance

#1910 Style the error boundaries component
  packages/files-ui/src/App.tsx
  packages/files-ui/src/Components/Modules/ErrorModal.tsx
Labels: Type: Bug Fix

#1899 Add new ui tests for annual and monthly billing options
  packages/files-ui/cypress/support/page-objects/modals/billing/planDetailsModal.ts
  packages/files-ui/cypress/tests/subscription-plan-spec.ts
Labels: Type: Maintenance, Status: Review Needed 👀

#1900 Pay invoice manually
  packages/files-ui/src/Components/Elements/InvoiceLines.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/ConfirmPlan.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx
  packages/files-ui/src/Components/Pages/BillingHistory.tsx
  packages/files-ui/src/Contexts/BillingContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1919 Add ui test for downgrading subscription plan
  packages/files-ui/cypress/support/page-objects/modals/billing/downgradeDetailsModal.ts
  packages/files-ui/cypress/support/page-objects/modals/billing/selectPlanModal.ts
  packages/files-ui/cypress/support/page-objects/settingsPage.ts
  packages/files-ui/cypress/tests/subscription-plan-spec.ts
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/DowngradeDetails.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentPlan.tsx
Labels: Type: Maintenance, Status: Review Needed 👀

#1923 Clear error message when the charge got rejected
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/utils/formatSubscriptionError.ts
Labels: Type: Bug Fix, Status: Review Needed 👀

#1924 Add info messages before payment and on downgrade
  packages/files-ui/cypress/support/page-objects/modals/billing/downgradeDetailsModal.ts
  packages/files-ui/cypress/support/page-objects/modals/billing/planChangeConfirmationModal.ts
  packages/files-ui/cypress/tests/subscription-plan-spec.ts
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/DowngradeDetails.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/ConfirmPlan.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/CryptoPayment.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance

#1925 Fix User Profile Button text overflow
  packages/files-ui/src/Components/Layouts/AppNav.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1927 New sharing design
  packages/common-components/src/Icons/icons/Link.icon.tsx
  packages/common-components/src/Icons/index.ts
  packages/common-components/src/Icons/svgs/link.svg
  packages/files-ui/cypress/support/page-objects/modals/createSharedFolderModal.ts
  packages/files-ui/cypress/tests/file-sharing-spec.ts
  packages/files-ui/cypress/tests/link-sharing-spec.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrManageSharedFolder.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrManageSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/Sharing/LinkList.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/Sharing/PermissionsDropdown.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/Sharing/SharingLink.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useCreateOrEditSharedFolder.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useLookupUser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/types.ts
  packages/files-ui/src/Components/Modules/LinkSharingModule.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance

#1933 Add ui test for crypto payment flow initiation and return
  packages/files-ui/cypress/support/page-objects/billingHistoryPage.ts
  packages/files-ui/cypress/support/page-objects/modals/billing/cryptoPaymentModal.ts
  packages/files-ui/cypress/support/page-objects/modals/billing/planChangeConfirmationModal.ts
  packages/files-ui/cypress/support/page-objects/settingsPage.ts
  packages/files-ui/cypress/tests/subscription-plan-spec.ts
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/ConfirmPlan.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/CryptoPayment.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance

#1878 Proration and credit calculated amounts
  packages/files-ui/package.json
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/ConfirmPlan.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/storage-ui/package.json
  yarn.lock
Labels: Type: Feature

#1934 Adapt Settings to the design and split the Display and Profile settings
  packages/files-ui/src/Components/Elements/InvoiceLines.tsx
  packages/files-ui/src/Components/FilesRoutes.tsx
  packages/files-ui/src/Components/Modules/Settings/DisplayTab/LanguageSelection.tsx
  packages/files-ui/src/Components/Modules/Settings/DisplayTab/index.tsx
  packages/files-ui/src/Components/Modules/Settings/ProfileTab/index.tsx
  packages/files-ui/src/Components/Modules/Settings/SecurityTab/SavedBrowsers/BrowserPanel.tsx
  packages/files-ui/src/Components/Modules/Settings/SecurityTab/SavedBrowsers/index.tsx
  packages/files-ui/src/Components/Modules/Settings/SecurityTab/index.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentCard.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentPlan.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/index.tsx
  packages/files-ui/src/Components/Modules/Settings/index.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance

#1937 Remove team fake door
  packages/files-ui/src/Components/Elements/TeamModal.tsx
  packages/files-ui/src/Components/FilesRoutes.tsx
  packages/files-ui/src/Components/Layouts/AppHeader.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance, Status: Review Needed 👀

#1938 Update copy on crypto payment dialog
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/CryptoPayment.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1940 owner removed from shared with list
  packages/files-ui/src/Components/Elements/SharedUsers.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
Labels: Type: Maintenance

#1942 Subscription plan title - singular
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/index.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance

#1946 Settings back icon in mobile view
  packages/common-components/src/Icons/icons/CaretLeft.icon.tsx
  packages/common-components/src/Icons/index.ts
  packages/common-components/src/Icons/svgs/caret-left.svg
  packages/files-ui/src/Components/Modules/Settings/index.tsx
Labels: Status: Review Needed 👀, Type: Feature

#1948 Files Billing soft launch
  packages/common-components/src/Tabs/Tabs.tsx
  packages/files-ui/cypress/tests/subscription-plan-spec.ts
  packages/files-ui/package.json
  packages/files-ui/src/Components/Modules/Settings/index.tsx
  packages/files-ui/src/Contexts/BillingContext.tsx
  packages/files-ui/src/locales/fr/messages.po
  packages/storage-ui/package.json
  yarn.lock
Labels: Status: Review Needed 👀, Type: Feature

#1947 exit and refresh the billing plan when the time is up
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/ConfirmPlan.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/CryptoPayment.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx
  packages/files-ui/src/Contexts/BillingContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Bug Fix

#1953 Refactor shared folder creation
  packages/files-ui/cypress/support/page-objects/modals/createSharedFolderModal.ts
  packages/files-ui/cypress/support/page-objects/modals/editSharedFolderModal.ts
  packages/files-ui/cypress/support/page-objects/sharedPage.ts
  packages/files-ui/cypress/tests/file-sharing-spec.ts
  packages/files-ui/cypress/tests/link-sharing-spec.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ManageSharedFolder.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ManageSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/types.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Bug Fix

#1957 Comment out name inputs in user profile
  packages/files-ui/cypress/tests/settings-spec.ts
  packages/files-ui/src/Components/Modules/Settings/ProfileTab/index.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance

#1958 Add ui test for downgrade plan selection
  packages/files-ui/cypress/support/page-objects/modals/billing/selectPlanModal.ts
  packages/files-ui/cypress/tests/subscription-plan-spec.ts
Labels: Type: Maintenance

#1955 Align new shared folder design with other modals
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Bug Fix, Status: Review Needed 👀

#1963 Circular progress bar fix.
  packages/common-components/src/ProgressBar/CircularProgressBar.tsx
Labels: Type: Bug Fix

#1960 File preview updates
  packages/common-components/src/Icons/icons/CaretCircleLeft.icon.tsx
  packages/common-components/src/Icons/icons/CaretCircleRight.icon.tsx
  packages/common-components/src/Icons/icons/File.icon.tsx
  packages/common-components/src/Icons/icons/FileAudio.icon.tsx
  packages/common-components/src/Icons/icons/FileVideo.icon.tsx
  packages/common-components/src/Icons/index.ts
  packages/common-components/src/Icons/svgs/caret-circle-left.svg
  packages/common-components/src/Icons/svgs/caret-circle-right.svg
  packages/common-components/src/Icons/svgs/file-audio.svg
  packages/common-components/src/Icons/svgs/file-pdf.svg
  packages/common-components/src/Icons/svgs/file-text.svg
  packages/common-components/src/Icons/svgs/file-video.svg
  packages/files-ui/cypress/support/page-objects/modals/previewModal.ts
  packages/files-ui/cypress/tests/file-preview-spec.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FilePreviewModal.tsx
  packages/files-ui/src/Components/Modules/PreviewRenderers/ImagePreview.tsx
  packages/files-ui/src/Components/Modules/PreviewRenderers/PDFPreview.tsx
  packages/files-ui/src/Components/Modules/PreviewRenderers/TextPreview.tsx
  packages/files-ui/src/Utils/getItemIcon.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Feature

#1972 Fix lgtm warning
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
Labels: Type: Bug Fix

#1973 Fix colors and qr code border
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/CryptoPayment.tsx
Labels: Type: Bug Fix

#1959 Access to the subscription whitelist button
  packages/files-ui/src/Components/Elements/BetaModal.tsx
  packages/files-ui/src/Components/FilesRoutes.tsx
  packages/files-ui/src/Components/Layouts/AppHeader.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance

#1980 Grid icons fix
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
Labels: Type: Bug Fix

#1977 Link to form instead of Discord
  packages/files-ui/src/Components/Elements/BetaModal.tsx
Labels: Type: Bug Fix

#1965 Make Storage tests pass
  packages/files-ui/cypress/support/utils/apiTestHelper.ts
  packages/storage-ui/cypress/support/commands.ts
  packages/storage-ui/cypress/support/index.ts
  packages/storage-ui/cypress/support/page-objects/bucketsPage.ts
  packages/storage-ui/cypress/support/utils/CustomBridge.ts
  packages/storage-ui/cypress/support/utils/apiTestHelper.ts
  packages/storage-ui/cypress/tests/bucket-management-spec.ts
  packages/storage-ui/cypress/tests/cid-management-spec.ts
  packages/storage-ui/src/Components/Pages/BucketsPage.tsx
  packages/storage-ui/src/Contexts/StorageContext.tsx
Labels: Type: Bug Fix

#1978 Focus colors on buttons
  packages/common-components/src/Button/Button.tsx
  packages/common-components/src/Icons/SvgIcon.tsx
  packages/files-ui/src/Components/Elements/Notifications/NotificationsDropdown.tsx
  packages/files-ui/src/Components/Elements/ShareTransferRequestModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/FileInfoModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ManageSharedFolder.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/MoveFileModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ReportFileModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Modules/FilePreviewModal.tsx
  packages/files-ui/src/Components/Modules/PreviewRenderers/ImagePreview.tsx
  packages/files-ui/src/Components/Modules/PreviewRenderers/PDFPreview.tsx
  packages/files-ui/src/Components/Modules/PreviewRenderers/TextPreview.tsx
  packages/files-ui/src/Components/Modules/Settings/SecurityTab/SavedBrowsers/BrowserPanel.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/AddCard.tsx
  packages/files-ui/src/Themes/Constants.ts
  packages/files-ui/src/Themes/DarkTheme.ts
  packages/files-ui/src/Themes/LightTheme.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Bug Fix

#1990 Fix sorting for shared folders
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
Labels: Type: Bug Fix
