Repository ChainSafe/ui-monorepo, pull requests merged in 2022-04, with the labels that each got.

#2054 File rename refactor
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemGridItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/Contexts/FileBrowserContext.tsx
Labels: Type: Bug Fix

#2042 Header titles added
  packages/files-ui/src/App.tsx
  packages/files-ui/src/Components/FilesRoutes.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Pages/BillingHistory.tsx
  packages/files-ui/src/Components/Pages/BinPage.tsx
  packages/files-ui/src/Components/Pages/DrivePage.tsx
  packages/files-ui/src/Components/Pages/LinkSharingLanding.tsx
  packages/files-ui/src/Components/Pages/SearchPage.tsx
  packages/files-ui/src/Components/Pages/SettingsPage.tsx
  packages/files-ui/src/Components/Pages/SharedFoldersPage.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/storage-ui/src/App.tsx
  packages/storage-ui/src/Components/Pages/BillingHistory.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/Components/Pages/BucketsPage.tsx
  packages/storage-ui/src/Components/Pages/CidsPage.tsx
  packages/storage-ui/src/Components/Pages/SettingsPage.tsx
  packages/storage-ui/src/locales/en/messages.po
Labels: Type: Maintenance

#2065 Bump axios to the latest
  packages/files-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: Type: Maintenance

#2057 Allow for creation of CS FS Storage buckets
  packages/storage-ui/src/Components/Elements/BucketRow.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Pages/BucketsPage.tsx
  packages/storage-ui/src/Contexts/StorageContext.tsx
  packages/storage-ui/src/locales/en/messages.po
Labels: Status: Review Needed 👀

#2053 Block upload if size exceeds capacity
  packages/common-components/src/FileInput/FileInput.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/UploadFileModal.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#2063 Hover, selected states for App navigation
  packages/files-ui/src/Components/Layouts/AppNav.tsx
  packages/files-ui/src/Themes/Constants.ts
  packages/files-ui/src/Themes/DarkTheme.ts
  packages/files-ui/src/Themes/LightTheme.ts
  packages/storage-ui/src/Components/Layouts/AppNav.tsx
Labels: Type: Maintenance

#2048 Update CID ui tests
  packages/storage-ui/cypress/fixtures/storageTestData.ts
  packages/storage-ui/cypress/support/page-objects/cidsPage.ts
  packages/storage-ui/cypress/support/page-objects/modals/addCidModal.ts
  packages/storage-ui/cypress/tests/cid-management-spec.ts
  packages/storage-ui/src/Components/Elements/CidRow.tsx
  packages/storage-ui/src/Components/Modules/AddCIDModal.tsx
Labels: Type: Maintenance

#2073 Add new ui tests for cid searching
  packages/storage-ui/cypress/fixtures/storageTestData.ts
  packages/storage-ui/cypress/support/page-objects/cidsPage.ts
  packages/storage-ui/cypress/tests/cid-management-spec.ts
  packages/storage-ui/src/Components/Elements/CidRow.tsx
  packages/storage-ui/src/Components/Pages/CidsPage.tsx
Labels: Type: Maintenance, Status: Review Needed 👀

#2067 Prevent drag when rename
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
Labels: Type: Bug Fix

#2075 Cancel any action and remove any toast on logout
  packages/common-components/package.json
  packages/common-components/rollup.config.js
  packages/common-components/src/Toasts/ToastContext.tsx
  packages/files-ui/package.json
  packages/files-ui/src/Components/Layouts/AppNav.tsx
  packages/files-ui/src/Contexts/NotificationsContext.tsx
  packages/storage-ui/package.json
  packages/storage-ui/src/Components/Layouts/AppHeader.tsx
  yarn.lock
Labels: Type: Bug Fix

#2074 UI layout adjustments and sticky bulk actions
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFoldersOverview.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Modules/Settings/index.tsx
  packages/files-ui/src/Themes/Constants.ts
  packages/files-ui/src/Themes/DarkTheme.ts
  packages/files-ui/src/Themes/LightTheme.ts
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Pages/BucketsPage.tsx
  packages/storage-ui/src/Components/Pages/CidsPage.tsx
  packages/storage-ui/src/Themes/Constants.ts
Labels: Type: Feature

#2080 Enable shared folder update button to close the modal
  packages/files-ui/src/Components/Modules/FileBrowsers/ManageSharedFolder.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/Sharing/LinkList.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/Sharing/SharingLink.tsx
Labels: Type: Bug Fix

#2081 Style ErrorBoundaries and remove hotjar
  packages/files-ui/.env.example
  packages/storage-ui/.env.example
  packages/storage-ui/package.json
  packages/storage-ui/src/App.tsx
  packages/storage-ui/src/Components/Modules/ErrorModal.tsx
  yarn.lock
Labels: Type: Bug Fix

#2072 Add ui test for blocked uploading when storage exceeded
  packages/common-components/src/FileInput/FileInput.tsx
  packages/files-ui/cypress/support/commands.ts
  packages/files-ui/cypress/support/page-objects/modals/fileUploadModal.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
Labels: Type: Maintenance, Status: Review Needed 👀, Product: Files

#2101 Prevent multiple file/folder renames [storage]
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemGridItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/Contexts/FileBrowserContext.tsx
Labels: Type: Feature

#2106 Fix double slash when uploading a file
  packages/files-ui/src/Components/Modules/FileBrowsers/UploadFileModal.tsx
  packages/files-ui/src/Utils/pathUtils.ts
Labels: Type: Bug Fix

#2084 DnD on storage
  packages/common-components/src/Breadcrumb/Breadcrumb.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/storage-ui/src/App.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemItem.tsx
  packages/storage-ui/src/Components/Modules/FilesList/DragPreviewLayer.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FolderBreadcrumb.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/Utils/getItemIcon.ts
  packages/storage-ui/src/Utils/pathUtils.ts
Labels: Type: Bug Fix
