Repository ChainSafe/ui-monorepo, pull requests merged in 2022-06, with the labels that each got.

#2160 [Files] Copy to clipboard Wallet address and Files sharing key test
  packages/files-ui/cypress/support/page-objects/settingsPage.ts
  packages/files-ui/cypress/tests/settings-spec.ts
  packages/files-ui/src/Components/Modules/Settings/ProfileTab/index.tsx
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
Labels: Type: Maintenance

#2165 Upload folders on drops [storage]
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/Contexts/StorageContext.tsx
  packages/storage-ui/src/Utils/getFilesFromDataTransferItems.ts
  packages/storage-ui/src/locales/en/messages.po
Labels: Type: Feature

#2162 [Files] Change to dark theme and go back to light theme test
  packages/files-ui/cypress/support/page-objects/settingsPage.ts
  packages/files-ui/cypress/tests/settings-spec.ts
  packages/files-ui/src/Components/Modules/Settings/DisplayTab/index.tsx
Labels: Type: Maintenance

#2166 Mnt/add redirection in navigation bar test 2142
  packages/files-ui/cypress/tests/landing-spec.ts
  packages/storage-ui/cypress/support/page-objects/navigationMenu.ts
  packages/storage-ui/cypress/tests/landing-spec.ts
  packages/storage-ui/cypress/tests/main-navigation-spec.ts
Labels: Type: Maintenance

#2125 NFT Metadata form
  .github/workflows/test-files-on-demand.yml
  .github/workflows/test-files.yml
  .github/workflows/test-storage-on-demand.yml
  .github/workflows/test-storage.yml
  packages/common-components/src/FileInput/FileInput.tsx
  packages/common-components/src/Icons/icons/UploadRound.icon.tsx
  packages/common-components/src/Icons/index.ts
  packages/common-components/src/Icons/svgs/upload-round.svg
  packages/files-ui/package.json
  packages/files-ui/src/Components/FilesRoutes.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/UploadFileModal.tsx
  packages/storage-ui/package.json
  packages/storage-ui/src/Components/Elements/FormikImageInput.tsx
  packages/storage-ui/src/Components/Pages/UploadNFTPage.tsx
  packages/storage-ui/src/Components/StorageRoutes.tsx
  packages/storage-ui/src/locales/en/messages.po
  yarn.lock
Labels: Type: Feature

#2180 Reroute to buckets on logo
  packages/storage-ui/src/Components/Layouts/AppNav.tsx
Labels: Type: Bug Fix

#2185 Nav style fixes for storage mobile view
  packages/storage-ui/src/Components/Layouts/AppNav.tsx
  packages/storage-ui/src/Components/Pages/BucketsPage.tsx
  packages/storage-ui/src/Themes/Constants.ts
  packages/storage-ui/src/Themes/LightTheme.ts
Labels: Type: Bug Fix

#2182 [Files] Sort by name, date uploaded or size test
  packages/files-ui/cypress/tests/file-management-spec.ts
Labels: Type: Maintenance

#2186 Hide gateway link when a CID is not yet pinned
  packages/storage-ui/src/Components/Elements/CidRow.tsx
Labels: Type: Bug Fix

#2192 [Files] Change language test
  packages/files-ui/cypress/support/page-objects/settingsPage.ts
  packages/files-ui/cypress/tests/settings.cy.ts
  packages/files-ui/src/Components/Modules/Settings/DisplayTab/LanguageSelection.tsx
  packages/files-ui/src/Components/Modules/Settings/index.tsx
Labels: Type: Maintenance

#2193 Navigation position style fixes [storage]
  packages/storage-ui/src/Components/Elements/CidRow.tsx
  packages/storage-ui/src/Components/Pages/CidsPage.tsx
Labels: Type: Bug Fix

#2200 [Storage] Skip navigate to the docs test
  packages/storage-ui/cypress/tests/main-navigation.cy.ts
Labels: Type: Maintenance

#2196 storage navigation refactor
  packages/common-components/src/Icons/icons/CreditCardOutlined.icon.tsx
  packages/common-components/src/Icons/index.ts
  packages/common-components/src/Icons/svgs/credit-card-outlined.svg
  packages/common-components/src/Icons/svgs/key.svg
  packages/storage-ui/cypress/support/page-objects/navigationMenu.ts
  packages/storage-ui/cypress/tests/main-navigation.cy.ts
  packages/storage-ui/src/Components/Layouts/AppHeader.tsx
  packages/storage-ui/src/Components/Layouts/AppNav.tsx
  packages/storage-ui/src/Components/Modules/ApiKeys.tsx
  packages/storage-ui/src/Components/Modules/SubscriptionTab/index.tsx
  packages/storage-ui/src/Components/Pages/ApiKeysPage.tsx
  packages/storage-ui/src/Components/Pages/SubscriptionPage.tsx
  packages/storage-ui/src/Components/StorageRoutes.tsx
  packages/storage-ui/src/locales/en/messages.po
Labels: Type: Feature

#2208 Sort CIDs table test
  packages/storage-ui/cypress/support/page-objects/cidsPage.ts
  packages/storage-ui/cypress/tests/cid-management.cy.ts
  packages/storage-ui/src/Components/Pages/CidsPage.tsx
Labels: Type: Maintenance

#2207 sort Buckets table test
  packages/storage-ui/cypress/support/page-objects/bucketsPage.ts
  packages/storage-ui/cypress/support/utils/TestConstants.ts
  packages/storage-ui/cypress/tests/bucket-management.cy.ts
  packages/storage-ui/src/Components/Pages/BucketsPage.tsx
Labels: Type: Maintenance
