Repository ChainSafe/ui-monorepo, pull requests merged in 2022-03, with the labels that each got.

#1983 Billing storage
  packages/storage-ui/src/App.tsx
  packages/storage-ui/src/Components/CustomButton.tsx
  packages/storage-ui/src/Components/Elements/InvoiceLines.tsx
  packages/storage-ui/src/Components/Modules/SubscriptionTab/AddCard/AddCardModal.tsx
  packages/storage-ui/src/Components/Modules/SubscriptionTab/BillingHistory.tsx
  packages/storage-ui/src/Components/Modules/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
  packages/storage-ui/src/Components/Modules/SubscriptionTab/ChangePlan/DowngradeDetails.tsx
  packages/storage-ui/src/Components/Modules/SubscriptionTab/ChangePlan/PaymentMethodSelector.tsx
  packages/storage-ui/src/Components/Modules/SubscriptionTab/ChangePlan/PlanDetails.tsx
  packages/storage-ui/src/Components/Modules/SubscriptionTab/ChangePlan/PlanSuccess.tsx
  packages/storage-ui/src/Components/Modules/SubscriptionTab/ChangePlan/SelectPlan.tsx
  packages/storage-ui/src/Components/Modules/SubscriptionTab/Common/AddCard.tsx
  packages/storage-ui/src/Components/Modules/SubscriptionTab/Common/ConfirmPlan.tsx
  packages/storage-ui/src/Components/Modules/SubscriptionTab/Common/CryptoPayment.tsx
  packages/storage-ui/src/Components/Modules/SubscriptionTab/CurrentCard.tsx
  packages/storage-ui/src/Components/Modules/SubscriptionTab/CurrentPlan.tsx
  packages/storage-ui/src/Components/Modules/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx
  packages/storage-ui/src/Components/Modules/SubscriptionTab/index.tsx
  packages/storage-ui/src/Components/Modules/SubscriptionTab/utils/formatSubscriptionError.ts
  packages/storage-ui/src/Components/Pages/BillingHistory.tsx
  packages/storage-ui/src/Components/Pages/SettingsPage.tsx
  packages/storage-ui/src/Components/StorageRoutes.tsx
  packages/storage-ui/src/Contexts/BillingContext.tsx
  packages/storage-ui/src/Themes/Constants.ts
  packages/storage-ui/src/Themes/DarkTheme.ts
  packages/storage-ui/src/Themes/LightTheme.ts
  packages/storage-ui/src/locales/en/messages.po
Labels: Status: Review Needed 👀, Type: Feature

#1995 Pdf viewer fixes
  packages/files-ui/src/Components/Modules/PreviewRenderers/PDFPreview.tsx
Labels: Type: Bug Fix, Status: Review Needed 👀

#1999 Remove edit access user fix
  packages/files-ui/src/Components/Modules/FileBrowsers/ManageSharedFolder.tsx
Labels: Type: Bug Fix

#1996 Refactor shared folder cretation and edition
  packages/files-ui/src/Components/Elements/SharedUsers.tsx
  packages/files-ui/src/Components/Elements/UserName.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ManageSharedFolder.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useCreateOrEditSharedFolder.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useLookupUser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/types.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/Utils/getUserDisplayName.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Bug Fix, Status: Review Needed 👀

#1976 Handle successful local Crypto Payment
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/ConfirmPlan.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/CryptoPayment.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/PlanSuccess.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Feature

#2003 Handle overflow on grid names
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
Labels: Type: Bug Fix

#2002 Access right options while lookup - manage shared folder
  packages/files-ui/src/Components/Modules/FileBrowsers/ManageSharedFolder.tsx
Labels: Type: Bug Fix

#2001 Use toggle for account visibility
  packages/common-components/src/ToggleSwitch/ToggleSwitch.tsx
  packages/files-ui/src/Components/Modules/Settings/ProfileTab/index.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀

#1991 Update product names
  packages/files-ui/cypress/support/page-objects/modals/billing/planChangeSuccessModal.ts
  packages/files-ui/cypress/support/page-objects/modals/billing/selectPlanModal.ts
  packages/files-ui/cypress/support/page-objects/settingsPage.ts
  packages/files-ui/cypress/tests/subscription-plan-spec.ts
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/DowngradeDetails.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/SelectPlan.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/PlanSuccess.tsx
  packages/files-ui/src/Contexts/BillingContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/storage-ui/src/Components/Modules/SubscriptionTab/ChangePlan/PlanSuccess.tsx
Labels: Type: Bug Fix

#2007 fix dialog closing instead of going to success
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/CryptoPayment.tsx
Labels: Type: Bug Fix

#2008 Resolve yarn.lock issue in gh actions test jobs
  .github/workflows/test-files-on-demand.yml
  .github/workflows/test-files.yml
  .github/workflows/test-storage.yml
Labels: Type: Maintenance

#2009 update tkey
  packages/files-ui/package.json
  packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
  packages/files-ui/src/Components/Modules/LoginModule/SaveNewDevice.tsx
  packages/files-ui/src/Contexts/ThresholdKeyContext.tsx
  yarn.lock
Labels: Priority: P0 Critical, Type: Maintenance

#2005 [Storage] Fix login screen and nav bar
  packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
  packages/storage-ui/src/Components/Layouts/AppNav.tsx
  packages/storage-ui/src/Components/Modules/LoginModule.tsx
  packages/storage-ui/src/Components/Pages/LoginPage.tsx
Labels: Type: Bug Fix

#1944 Create Posthog event to measure how often folders are shared manually vs with a link
  packages/files-ui/src/Components/Modules/FileBrowsers/ManageSharedFolder.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/Sharing/LinkList.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useLookupUser.tsx
  packages/files-ui/src/Components/Modules/LinkSharingModule.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance

#2016 Upgrade caniuse and cypress
  packages/files-ui/package.json
  packages/storage-ui/package.json
  yarn.lock
Labels: Type: Maintenance

#2015 Storage UI Overhaul
  packages/storage-ui/package.json
  packages/storage-ui/src/Components/Elements/Notifications/NotificationLine.tsx
  packages/storage-ui/src/Components/Elements/Notifications/NotificationList.tsx
  packages/storage-ui/src/Components/Elements/Notifications/NotificationsDropdown.tsx
  packages/storage-ui/src/Components/Layouts/AppHeader.tsx
  packages/storage-ui/src/Components/Layouts/AppNav.tsx
  packages/storage-ui/src/Components/Modules/ApiKeys.tsx
  packages/storage-ui/src/Components/Pages/SettingsPage.tsx
  packages/storage-ui/src/Themes/Constants.ts
  packages/storage-ui/src/Themes/DarkTheme.ts
  packages/storage-ui/src/Themes/LightTheme.ts
  packages/storage-ui/src/locales/en/messages.po
  yarn.lock
Labels: Type: Feature

#2027 [Storage] Add warning when pinning a cid twice
  packages/storage-ui/src/Components/Modules/AddCIDModal.tsx
  packages/storage-ui/src/Contexts/StorageContext.tsx
  packages/storage-ui/src/locales/en/messages.po
Labels: Type: Maintenance

#2028 add Posthog to storage
  packages/storage-ui/src/App.tsx
  packages/storage-ui/src/Components/Pages/BillingHistory.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/Components/Pages/BucketsPage.tsx
  packages/storage-ui/src/Components/Pages/CidsPage.tsx
  packages/storage-ui/src/Components/Pages/LoginPage.tsx
  packages/storage-ui/src/Components/Pages/SettingsPage.tsx
  packages/storage-ui/src/Contexts/PosthogContext.tsx
  packages/storage-ui/src/Themes/Constants.ts
  packages/storage-ui/src/Themes/DarkTheme.ts
  packages/storage-ui/src/Themes/LightTheme.ts
  packages/storage-ui/src/index.tsx
  packages/storage-ui/src/locales/en/messages.po
Labels: Type: Feature

#2031 [Storage] Restricted mode banner and flow
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/storage-ui/src/Components/Elements/RestrictedModeBanner.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/Components/Pages/BucketsPage.tsx
  packages/storage-ui/src/Components/Pages/CidsPage.tsx
  packages/storage-ui/src/Contexts/BillingContext.tsx
  packages/storage-ui/src/Contexts/StorageApiContext.tsx
  packages/storage-ui/src/locales/en/messages.po
Labels: Type: Maintenance

#2019 Add ui tests for notifications
  packages/files-ui/cypress/fixtures/cardData.ts
  packages/files-ui/cypress/support/commands.ts
  packages/files-ui/cypress/support/page-objects/basePage.ts
  packages/files-ui/cypress/support/page-objects/settingsPage.ts
  packages/files-ui/cypress/support/utils/apiTestHelper.ts
  packages/files-ui/cypress/tests/notifications-spec.ts
  packages/files-ui/cypress/tests/subscription-plan-spec.ts
  packages/files-ui/cypress/tsconfig.json
  packages/files-ui/src/Components/Elements/Notifications/NotificationLine.tsx
  packages/files-ui/src/Components/Elements/Notifications/NotificationList.tsx
  packages/files-ui/src/Components/Elements/Notifications/NotificationsDropdown.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/DowngradeDetails.tsx
  packages/storage-ui/src/Components/Modules/SubscriptionTab/ChangePlan/DowngradeDetails.tsx
Labels: Type: Maintenance

#2033 Add retry mechanism for Storage tests
  packages/storage-ui/cypress.json
Labels: Type: Maintenance

#2032 Add ui tests for copying / moving to share folders
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/cypress/support/page-objects/modals/editSharedFolderModal.ts
  packages/files-ui/cypress/support/page-objects/modals/shareFileModal.ts
  packages/files-ui/cypress/support/page-objects/sharedPage.ts
  packages/files-ui/cypress/support/page-objects/toasts/shareSuccessToast.ts
  packages/files-ui/cypress/support/page-objects/toasts/sharingProgressToast.ts
  packages/files-ui/cypress/support/utils/apiTestHelper.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/cypress/tests/file-preview-spec.ts
  packages/files-ui/cypress/tests/file-sharing-spec.ts
  packages/files-ui/cypress/tests/search-spec.ts
  packages/files-ui/cypress/tests/subscription-plan-spec.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/ManageSharedFolder.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
Labels: Type: Maintenance

#2035 Add non disabled note
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/PaymentMethodSelector.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/storage-ui/src/Components/Modules/SubscriptionTab/ChangePlan/PaymentMethodSelector.tsx
  packages/storage-ui/src/locales/en/messages.po
Labels: Type: Bug Fix

#2036 Allow to name pins and display such name
  packages/storage-ui/src/Components/Elements/CidRow.tsx
  packages/storage-ui/src/Components/Modules/AddCIDModal.tsx
  packages/storage-ui/src/Components/Modules/CreateFolderModal/CreateFolderModal.tsx
  packages/storage-ui/src/Components/Pages/CidsPage.tsx
  packages/storage-ui/src/Contexts/StorageContext.tsx
  packages/storage-ui/src/locales/en/messages.po
Labels: Type: Maintenance

#2041 Has mnemonic share check
  packages/files-ui/src/Contexts/ThresholdKeyContext.tsx
Labels: Status: Review Needed 👀, Product: Files

#2056 stage url update
  .github/workflows/test-files-on-demand.yml
  .github/workflows/test-files.yml
  .github/workflows/test-storage.yml
  packages/files-ui/.env.example
  packages/files-ui/cypress/support/utils/apiTestHelper.ts
  packages/files-ui/cypress/tests/survey-banner-spec.ts
  packages/files-ui/src/App.tsx
  packages/storage-ui/.env.example
  packages/storage-ui/cypress/support/utils/apiTestHelper.ts
  packages/storage-ui/src/App.tsx
Labels: Type: Maintenance

#2045 Add new session capability to storage tests
  packages/files-ui/cypress/support/index.ts
  packages/files-ui/src/locales/fr/messages.po
  packages/storage-ui/cypress/support/commands.ts
  packages/storage-ui/cypress/support/index.ts
Labels: Type: Maintenance

#2046 Allow search pin by name and cid
  .eslintrc.json
  package.json
  packages/common-components/src/SearchBar/SearchBar.tsx
  packages/files-ui/package.json
  packages/storage-ui/package.json
  packages/storage-ui/src/Components/Modules/AddCIDModal.tsx
  packages/storage-ui/src/Components/Pages/CidsPage.tsx
  packages/storage-ui/src/Contexts/StorageContext.tsx
  packages/storage-ui/src/locales/en/messages.po
  yarn.lock
Labels: Type: Feature
