Repository ChainSafe/ui-monorepo, pull requests merged in 2022-05, with the labels that each got.

#2113 Pipeline for executing Storage on demand ui tests
  .github/workflows/test-storage-on-demand.yml
Labels: Type: Maintenance

#2108 Upload files sequentially by path
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/UploadFileModal.tsx
Labels: Type: Bug Fix

#2107 Rename with extension [Storage]
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/files-ui/src/Utils/Helpers.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemGridItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
  packages/storage-ui/src/Utils/Helpers.tsx
Labels: Type: Feature

#2115 [Files] Add landing page tests
  packages/files-ui/cypress/support/page-objects/authenticationPage.ts
  packages/files-ui/cypress/tests/landing-spec.ts
  packages/files-ui/src/Components/Modules/LoginModule/InitialScreen.tsx
  packages/files-ui/src/Components/Pages/LoginPage.tsx
Labels: Type: Maintenance

#2117 Improve bucket upload ui tests
  packages/common-components/src/RadioInput/FormikRadioInput.tsx
  packages/files-ui/cypress/support/page-objects/modals/fileUploadModal.ts
  packages/storage-ui/cypress/fixtures/storageTestData.ts
  packages/storage-ui/cypress/support/page-objects/bucketContentsPage.ts
  packages/storage-ui/cypress/support/page-objects/bucketsPage.ts
  packages/storage-ui/cypress/support/page-objects/modals/createBucketModal.ts
  packages/storage-ui/cypress/support/page-objects/modals/fileUploadModal.ts
  packages/storage-ui/cypress/support/page-objects/toasts/uploadStatusToast.ts
  packages/storage-ui/cypress/tests/bucket-management-spec.ts
  packages/storage-ui/src/Components/Elements/BucketRow.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Modules/UploadFileModal/UploadFileModal.tsx
  packages/storage-ui/src/Components/Pages/BucketsPage.tsx
Labels: Type: Maintenance

#2109 shift key functionality for selections
  packages/common-components/src/CheckboxInput/CheckboxInput.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
Labels: Type: Feature

#2129 Extend timeout to improve storage test reliability
  packages/storage-ui/cypress/support/page-objects/bucketsPage.ts
Labels: Type: Maintenance

#2130 [Files] Add view file information modal test
  packages/files-ui/cypress/support/index.ts
  packages/files-ui/cypress/support/page-objects/modals/fileInfoModal.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/cypress/tests/main-navigation-spec.ts
  packages/files-ui/src/Components/Modules/FileBrowsers/FileInfoModal.tsx
  packages/storage-ui/cypress/support/index.ts
Labels: Type: Maintenance, Testing

#2138 Upload notification
  packages/common-components/src/FileInput/FileInput.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/SharedFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/UploadFileModal.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/Utils/getFilesFromDataTransferItems.ts
  packages/files-ui/src/locales/fr/messages.po
Labels: Type: Bug Fix

#2135 Bin view crumbs
  packages/files-ui/src/Components/Modules/FileBrowsers/BinFileBrowser.tsx
Labels: Type: Feature

#2145 Update Chrome version and fix Slack notification issue
  .github/workflows/test-files-on-demand.yml
  .github/workflows/test-files.yml
  .github/workflows/test-storage-on-demand.yml
  .github/workflows/test-storage.yml
Labels: Type: Maintenance

#2139 [Files] Add download file test
  packages/files-ui/cypress/support/page-objects/toasts/downloadCompleteToast.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/src/Contexts/FilesContext.tsx
Labels: Type: Maintenance

#2134 Right click context menu
  packages/common-components/src/MenuDropdown/MenuDropdown.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemGridItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemTableItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/itemOperations.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/UI-components/AnchorMenu.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemGridItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/FileSystemTableItem.tsx
  packages/storage-ui/src/Components/Modules/FileSystemItem/itemOperations.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/UI-components/AnchorMenu.tsx
  packages/storage-ui/src/Themes/Constants.ts
  packages/storage-ui/src/Themes/DarkTheme.ts
  packages/storage-ui/src/Themes/LightTheme.ts
  packages/storage-ui/src/locales/en/messages.po
Labels: Type: Feature

#2148 Add notification when storage is running low
  packages/files-ui/src/Components/Elements/Notifications/NotificationsDropdown.tsx
  packages/files-ui/src/Components/Layouts/AppHeader.tsx
  packages/files-ui/src/Contexts/BillingContext.tsx
  packages/files-ui/src/Contexts/NotificationsContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Feature

#2150 [Files] Add and improve Spanish translations
  packages/files-ui/src/Components/Layouts/AppNav.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateFolderModal.tsx
  packages/files-ui/src/Components/Modules/LoginModule/PasswordlessEmail.tsx
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.mo
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance

#2149 Toasts update for uploads and downloads [storage]
  packages/files-ui/src/Contexts/FilesContext.tsx
  packages/storage-ui/cypress/support/page-objects/toasts/uploadCompleteToast.ts
  packages/storage-ui/cypress/support/page-objects/toasts/uploadStatusToast.ts
  packages/storage-ui/cypress/tests/bucket-management-spec.ts
  packages/storage-ui/src/Components/Modules/DownloadProgressModals/DownloadBox.tsx
  packages/storage-ui/src/Components/Modules/DownloadProgressModals/index.tsx
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Modules/UploadProgressModals/UploadBox.tsx
  packages/storage-ui/src/Components/Modules/UploadProgressModals/index.tsx
  packages/storage-ui/src/Components/Pages/BucketPage.tsx
  packages/storage-ui/src/Contexts/FileBrowserContext.tsx
  packages/storage-ui/src/Contexts/FileOperationsReducers.tsx
  packages/storage-ui/src/Contexts/StorageContext.tsx
  packages/storage-ui/src/locales/en/messages.po
Labels: Type: Bug Fix

#2151 Add ui tests for change password
  packages/files-ui/cypress/fixtures/filesTestData.ts
  packages/files-ui/cypress/support/page-objects/settingsPage.ts
  packages/files-ui/cypress/tests/settings-spec.ts
  packages/files-ui/src/Components/Modules/Settings/SecurityTab/index.tsx
Labels: Type: Maintenance

#2154 Fix context menu on modals
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/SurveyBanner.tsx
  packages/files-ui/src/locales/fr/messages.po
  packages/storage-ui/src/Components/Modules/FilesList/FilesList.tsx
  packages/storage-ui/src/Components/Modules/SurveyBanner.tsx
Labels: Type: Bug Fix

#2157 `no-loop-func` lint warning fix
  packages/files-ui/src/Contexts/FilesContext.tsx
Labels: Type: Maintenance

#2158 Shared folders overview dropdown overflow fix
  packages/common-components/src/RadioInput/FormikRadioInput.tsx
  packages/common-components/src/SelectInput/SelectInput.tsx
  packages/common-components/src/stories/SelectInput.stories.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ShareModal.tsx
Labels: Type: Bug Fix
