Repository ChainSafe/ui-monorepo, pull requests merged in 2022-01, with the labels that each got.

#1838 Add spacing to theme selection box
  packages/files-ui/src/Components/Modules/Settings/ProfileTab/index.tsx
  packages/files-ui/src/locales/fr/messages.po
Labels: Type: Bug Fix, Status: Review Needed 👀

#1833 Show information when there are no notifications
  packages/common-components/src/Icons/icons/MoonStar.icon.tsx
  packages/common-components/src/Icons/index.ts
  packages/common-components/src/Icons/svgs/moon-star.svg
  packages/files-ui/src/Components/Elements/Notifications/NotificationList.tsx
  packages/files-ui/src/Components/Elements/Notifications/NotificationsDropdown.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance, Status: Review Needed 👀

#1837 TestId naming consistency
  packages/common-components/src/Button/Button.tsx
  packages/common-components/src/CheckboxInput/CheckboxInput.tsx
  packages/common-components/src/FileInput/FileInput.tsx
  packages/common-components/src/HamburgerMenu/HamburgerMenu.tsx
  packages/common-components/src/MenuDropdown/MenuDropdown.tsx
  packages/common-components/src/Modal/Modal.tsx
  packages/common-components/src/SearchBar/SearchBar.tsx
  packages/common-components/src/Table/Table.tsx
  packages/common-components/src/Tabs/Tabs.tsx
  packages/common-components/src/Toasts/ToastContent.tsx
  packages/files-ui/cypress/support/page-objects/basePage.ts
  packages/files-ui/cypress/support/page-objects/fileBrowser.ts
  packages/files-ui/cypress/support/page-objects/modals/createSharedFolderModal.ts
  packages/files-ui/cypress/support/page-objects/modals/deleteFileModal.ts
  packages/files-ui/cypress/support/page-objects/modals/deleteSharedFolderModal.ts
  packages/files-ui/cypress/support/page-objects/modals/fileUploadModal.ts
  packages/files-ui/cypress/support/page-objects/modals/leaveSharedFolderModal.ts
  packages/files-ui/cypress/support/page-objects/modals/previewModal.ts
  packages/files-ui/cypress/support/page-objects/settingsPage.ts
  packages/files-ui/cypress/support/page-objects/toasts/deleteSuccessToast.ts
  packages/files-ui/cypress/support/page-objects/toasts/moveSuccessToast.ts
  packages/files-ui/cypress/support/page-objects/toasts/profileUpdateSuccessToast.ts
  packages/files-ui/cypress/support/page-objects/toasts/recoverSuccessToast.ts
  packages/files-ui/cypress/support/page-objects/toasts/uploadCompleteToast.ts
  packages/files-ui/src/UI-components/Menu.tsx
  packages/storage-ui/cypress/support/page-objects/basePage.ts
  packages/storage-ui/cypress/support/page-objects/bucketsPage.ts
  packages/storage-ui/cypress/support/page-objects/cidsPage.ts
Labels: Type: Maintenance, Status: Review Needed 👀

#1834 Profile and username add tests
  packages/common-components/src/Button/Button.tsx
  packages/common-components/src/CheckboxInput/CheckboxInput.tsx
  packages/common-components/src/FileInput/FileInput.tsx
  packages/common-components/src/HamburgerMenu/HamburgerMenu.tsx
  packages/common-components/src/MenuDropdown/MenuDropdown.tsx
  packages/common-components/src/Modal/Modal.tsx
  packages/common-components/src/SearchBar/SearchBar.tsx
  packages/common-components/src/Table/Table.tsx
  packages/common-components/src/Tabs/Tabs.tsx
  packages/common-components/src/Toasts/ToastContent.tsx
  packages/files-ui/cypress/support/page-objects/basePage.ts
  packages/files-ui/cypress/support/page-objects/fileBrowser.ts
  packages/files-ui/cypress/support/page-objects/modals/createSharedFolderModal.ts
  packages/files-ui/cypress/support/page-objects/modals/deleteFileModal.ts
  packages/files-ui/cypress/support/page-objects/modals/deleteSharedFolderModal.ts
  packages/files-ui/cypress/support/page-objects/modals/fileUploadModal.ts
  packages/files-ui/cypress/support/page-objects/modals/leaveSharedFolderModal.ts
  packages/files-ui/cypress/support/page-objects/modals/previewModal.ts
  packages/files-ui/cypress/support/page-objects/settingsPage.ts
  packages/files-ui/cypress/support/page-objects/toasts/deleteSuccessToast.ts
  packages/files-ui/cypress/support/page-objects/toasts/moveSuccessToast.ts
  packages/files-ui/cypress/support/page-objects/toasts/profileUpdateSuccessToast.ts
  packages/files-ui/cypress/support/page-objects/toasts/recoverSuccessToast.ts
  packages/files-ui/cypress/support/page-objects/toasts/uploadCompleteToast.ts
  packages/files-ui/cypress/tests/settings-spec.ts
  packages/files-ui/src/Components/Modules/Settings/ProfileTab/index.tsx
  packages/files-ui/src/UI-components/Menu.tsx
  packages/storage-ui/cypress/support/page-objects/basePage.ts
  packages/storage-ui/cypress/support/page-objects/bucketsPage.ts
  packages/storage-ui/cypress/support/page-objects/cidsPage.ts
Labels: Type: Maintenance

#1832 Add link sharing to the sharing explainer
  packages/common-components/src/Modal/Modal.tsx
  packages/files-ui/cypress/support/page-objects/modals/sharingExplainerModal.ts
  packages/files-ui/cypress/tests/sharing-explainer-spec.ts
  packages/files-ui/src/Components/SharingExplainerModal.tsx
  packages/files-ui/src/Media/sharingExplainer/step3.png
  packages/files-ui/src/Media/sharingExplainer/step4.png
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance, Status: Review Needed 👀

#1839 Notifications context
  packages/files-ui/src/App.tsx
  packages/files-ui/src/Components/Elements/Notifications/NotificationsDropdown.tsx
  packages/files-ui/src/Components/Layouts/AppHeader.tsx
  packages/files-ui/src/Contexts/NotificationsContext.tsx
Labels: Status: Review Needed 👀, Type: Feature

#1841 Fix React warning with data attributes
  packages/common-components/src/Button/Button.tsx
  packages/common-components/src/CheckboxInput/CheckboxInput.tsx
  packages/common-components/src/FileInput/FileInput.tsx
  packages/common-components/src/HamburgerMenu/HamburgerMenu.tsx
  packages/common-components/src/MenuDropdown/MenuDropdown.tsx
  packages/common-components/src/Modal/Modal.tsx
  packages/common-components/src/SearchBar/SearchBar.tsx
  packages/common-components/src/Table/Table.tsx
  packages/common-components/src/Tabs/Tabs.tsx
  packages/common-components/src/Toasts/ToastContent.tsx
  packages/files-ui/cypress/support/page-objects/basePage.ts
  packages/files-ui/cypress/support/page-objects/binPage.ts
  packages/files-ui/cypress/support/page-objects/fileBrowser.ts
  packages/files-ui/cypress/support/page-objects/homePage.ts
  packages/files-ui/cypress/support/page-objects/modals/createSharedFolderModal.ts
  packages/files-ui/cypress/support/page-objects/modals/deleteFileModal.ts
  packages/files-ui/cypress/support/page-objects/modals/deleteSharedFolderModal.ts
  packages/files-ui/cypress/support/page-objects/modals/fileUploadModal.ts
  packages/files-ui/cypress/support/page-objects/modals/leaveSharedFolderModal.ts
  packages/files-ui/cypress/support/page-objects/modals/moveItemModal.ts
  packages/files-ui/cypress/support/page-objects/modals/previewModal.ts
  packages/files-ui/cypress/support/page-objects/modals/recoverFileModal.ts
  packages/files-ui/cypress/support/page-objects/modals/recoverItemModal.ts
  packages/files-ui/cypress/support/page-objects/modals/sharingExplainerModal.ts
  packages/files-ui/cypress/support/page-objects/settingsPage.ts
  packages/files-ui/cypress/support/page-objects/toasts/deleteSuccessToast.ts
  packages/files-ui/cypress/support/page-objects/toasts/moveSuccessToast.ts
  packages/files-ui/cypress/support/page-objects/toasts/profileUpdateSuccessToast.ts
  packages/files-ui/cypress/support/page-objects/toasts/recoverSuccessToast.ts
  packages/files-ui/cypress/support/page-objects/toasts/uploadCompleteToast.ts
  packages/files-ui/src/UI-components/Menu.tsx
  packages/storage-ui/cypress/support/page-objects/basePage.ts
  packages/storage-ui/cypress/support/page-objects/bucketsPage.ts
  packages/storage-ui/cypress/support/page-objects/cidsPage.ts
Labels: Type: Maintenance, Status: Review Needed 👀

#1836 DnD with breadcrumbs
  packages/common-components/src/Breadcrumb/Breadcrumb.tsx
  packages/common-components/src/stories/Breadcrumb.stories.tsx
  packages/common-theme/rollup.config.js
  packages/files-ui/package.json
  packages/files-ui/src/App.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CSFFileBrowser.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FolderBreadcrumb.tsx
  packages/files-ui/src/Utils/pathUtils.ts
Labels: Type: Feature

#1849 Folders drag and drop
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
Labels: Type: Feature

#1853 Prevent file/folder movement in home breadcrumb in home
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FilesList.tsx
Labels: Type: Bug Fix

#1854 Notification button height
  packages/files-ui/src/Components/Elements/Notifications/NotificationsDropdown.tsx
Labels: Type: Bug Fix

#1855 Cookie banner styling
  packages/files-ui/src/Contexts/PosthogContext.tsx
Labels: Type: Bug Fix

#1844 Crypto Payment
  packages/common-components/src/Icons/icons/Bitcoin.icon.tsx
  packages/common-components/src/Icons/icons/Dai.icon.tsx
  packages/common-components/src/Icons/icons/Ethereum.icon.tsx
  packages/common-components/src/Icons/icons/Usdc.icon.tsx
  packages/common-components/src/Icons/index.ts
  packages/common-components/src/Icons/svgs/bitcoin.svg
  packages/common-components/src/Icons/svgs/dai.svg
  packages/common-components/src/Icons/svgs/ethereum.svg
  packages/common-components/src/Icons/svgs/usdc.svg
  packages/common-components/src/Modal/Modal.tsx
  packages/common-components/src/ProgressBar/CircularProgressBar.tsx
  packages/common-components/src/stories/ProgressBar.stories.tsx
  packages/files-ui/package.json
  packages/files-ui/src/App.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ConfirmPlan.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/CryptoPayment.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/DowngradeDetails.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/PaymentMethodSelector.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/PlanDetails.tsx
  packages/files-ui/src/Contexts/BillingContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/storage-ui/package.json
  yarn.lock
Labels: Status: Review Needed 👀, Type: Feature

#1862 Modal styles consistency
  packages/files-ui/src/Components/Elements/CustomModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrEditSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrManageSharedFolder.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrManageSharedFolderModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/FileInfoModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/MoveFileModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/ReportFileModal.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/FileSystemItem.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/views/FileSystemItem/SharedFolderRow.tsx
  packages/files-ui/src/Components/Modules/Settings/SecurityTab/SavedBrowsers/BrowserPanel.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCard/AddCard.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCard/AddCardModal.tsx
  packages/files-ui/src/Components/SharingExplainerModal.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance

#1843 add ui tests for add / update / remove card
  .github/workflows/test-files-on-demand.yml
  .github/workflows/test-files.yml
  packages/files-ui/cypress.json
  packages/files-ui/cypress/fixtures/cardData.ts
  packages/files-ui/cypress/support/commands.ts
  packages/files-ui/cypress/support/page-objects/modals/addCardModal.ts
  packages/files-ui/cypress/support/page-objects/modals/removeCardModal.ts
  packages/files-ui/cypress/support/page-objects/settingsPage.ts
  packages/files-ui/cypress/support/page-objects/toasts/cardAddedToast.ts
  packages/files-ui/cypress/support/page-objects/toasts/cardUpdatedToast.ts
  packages/files-ui/cypress/support/utils/apiTestHelper.ts
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/cypress/tests/main-navigation-spec.ts
  packages/files-ui/cypress/tests/subscription-plan-spec.ts
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCard/AddCard.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCard/AddCardModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentCard.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentPlan.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/index.tsx
Labels: Type: Maintenance, Status: Review Needed 👀

#1868 add ui test for checking invalid card details
  packages/files-ui/cypress/fixtures/cardData.ts
  packages/files-ui/cypress/tests/subscription-plan-spec.ts
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCard/AddCard.tsx
Labels: Type: Maintenance

#1864 add new ui tests for plan selection
  packages/common-components/src/ToggleSwitch/ToggleSwitch.tsx
  packages/files-ui/cypress/fixtures/cardData.ts
  packages/files-ui/cypress/support/page-objects/modals/addOrUpdateCardModal.ts
  packages/files-ui/cypress/support/page-objects/modals/planDetailsModal.ts
  packages/files-ui/cypress/support/page-objects/modals/selectPlanModal.ts
  packages/files-ui/cypress/support/page-objects/settingsPage.ts
  packages/files-ui/cypress/tests/subscription-plan-spec.ts
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCard/AddCard.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/PlanDetails.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/SelectPlan.tsx
  packages/files-ui/src/locales/fr/messages.po
Labels: Type: Maintenance, Status: Review Needed 👀

#1861 Billing notifications
  packages/files-ui/src/App.tsx
  packages/files-ui/src/Components/Elements/InvoiceLines.tsx
  packages/files-ui/src/Components/Elements/Notifications/NotificationList.tsx
  packages/files-ui/src/Contexts/BillingContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Status: Review Needed 👀

#1867 ENS lookup
  packages/files-ui/src/Components/Modules/FileBrowsers/CreateOrManageSharedFolder.tsx
  packages/files-ui/src/Components/Modules/FileBrowsers/hooks/useLookupUser.tsx
  packages/files-ui/src/Components/Modules/Settings/ProfileTab/index.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Feature

#1859 Allow users to go back to crypto payment
  packages/files-ui/package.json
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ConfirmPlan.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/CryptoPayment.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/SelectPlan.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentPlan.tsx
  packages/files-ui/src/Contexts/BillingContext.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  yarn.lock
Labels: Type: Maintenance, Status: Review Needed 👀

#1877 Programmacically get a user back to the free plan
  packages/files-ui/cypress/support/commands.ts
  packages/files-ui/cypress/support/utils/apiTestHelper.ts
  packages/files-ui/cypress/tests/subscription-plan-spec.ts
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/index.tsx
Labels: Type: Maintenance

#1876 [Fix] Remove the artificial 65 char limit and fix caption on black theme
  packages/common-components/src/TextInput/TextInput.tsx
  packages/files-ui/cypress/tests/file-management-spec.ts
  packages/files-ui/src/Utils/validationSchema.ts
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/storage-ui/src/Utils/validationSchema.ts
  packages/storage-ui/src/locales/en/messages.po
Labels: Type: Bug Fix, Status: Review Needed 👀

#1866 Pay Invoice
  packages/files-ui/src/Components/Elements/InvoiceLines.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/AddCard/AddCardModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/BillingHistory.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/ChangePlanModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/PaymentMethodSelector.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/PlanDetails.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/SelectPlan.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/AddCard.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/ConfirmPlan.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/CryptoPayment.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/CurrentPlan.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/PayInvoice/PayInvoiceModal.tsx
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/index.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Feature

#1879 Fix Posthog Identify integration
  packages/files-ui/craco.config.js
  packages/files-ui/package.json
  packages/files-ui/src/Contexts/PosthogContext.tsx
  yarn.lock
Labels: Type: Bug Fix

#1872 Plan details yearly monthly styles
  packages/common-components/src/ToggleSwitch/ToggleSwitch.tsx
  packages/files-ui/cypress/support/page-objects/modals/planDetailsModal.ts
  packages/files-ui/cypress/tests/subscription-plan-spec.ts
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/ChangePlan/PlanDetails.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
Labels: Type: Maintenance

#1887 Fix placeholder in dark mode and cleanup
  packages/files-ui/src/Components/Elements/CardInputs/index.tsx
  packages/files-ui/src/Components/Elements/CardInputs/utils/cardTypes.ts
  packages/files-ui/src/Components/Elements/CardInputs/utils/formatter.ts
  packages/files-ui/src/Components/Elements/CardInputs/utils/index.ts
  packages/files-ui/src/Components/Elements/CardInputs/utils/validator.ts
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/AddCard.tsx
  packages/files-ui/src/Themes/Constants.ts
  packages/files-ui/src/Themes/DarkTheme.ts
  packages/files-ui/src/Themes/LightTheme.ts
  packages/files-ui/src/locales/fr/messages.po
Labels: Type: Bug Fix

#1893 Streamline loader when paying with crypto
  packages/files-ui/src/Components/Modules/Settings/SubscriptionTab/Common/CryptoPayment.tsx
Labels: Type: Bug Fix

#1886 Add invoice detail fields to Invoice Item
  packages/common-components/src/Button/Button.tsx
  packages/files-ui/package.json
  packages/files-ui/src/Components/Elements/InvoiceLines.tsx
  packages/files-ui/src/locales/de/messages.po
  packages/files-ui/src/locales/en/messages.po
  packages/files-ui/src/locales/es/messages.po
  packages/files-ui/src/locales/fr/messages.po
  packages/files-ui/src/locales/no/messages.po
  packages/storage-ui/package.json
  yarn.lock
Labels: Status: Review Needed 👀, Type: Feature
